### ISSUE TITLE
Larger icon sizes missing in platform branding UI

### ISSUE THREAD

**Issue by aldobrucale** [apache/netbeans#3544]
### Apache NetBeans version

Latest release candidate

### What happened

Changing the custom icon for a platform app doesnt'have any effect, and the default Netbeans icon is used instead.

It must be a problem with the harness, because it still works if the application uses the 9.0 platform, but not with platforms 12.5, 12.6 or 13.0-rc2

### How to reproduce

Create a Netbeans Platform App project using a recent version of the platform (I've tried from 12.5 on), change the icons and run the program. The custom icons are ignored.

### Did this work correctly in an earlier version?

- [X] This used to work!

### Operating System

Ubuntu 20.04 but it shouldn't be related

### JDK

JDK 11

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Id doesn't actually depend on the ide version, but on the platform version

### Are you willing to submit a pull request?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by neilcsmith-net** [comment]
You mean the icons in the branding dialog, Basic section?  The UI needs an update I think as higher resolution icons have been added to the IDE.  The harness itself is OK.

Go into the branding folder, `<project>/branding/core/core.jar/org/netbeans/core/startup/` and make sure you have files for `frame256.png`, `frame512.png` and `frame1024.png`.

**Comment by aldobrucale** [comment]
I didn't have those larger icons: I've added them and now everything works as expected. Without an UI update the user has no clue about the need for these image sizes.

**Comment by neilcsmith-net** [comment]
@aldobrucale yes, caught me out the first time! Thanks for confirmation it's just the UI. Updated labelling and title. Hopefully an easy fix. although may also need consideration of SVG support. cc/ @ralphbenjamin @eirikbakke

**Comment by eirikbakke** [comment]
The SVG support stuff does not affect the branding files (it's too early in the startup sequence to support SVG graphics here). 

But since after https://github.com/apache/netbeans/pull/1246 , you can supply a splash screen graphic that is twice the width/height of that specified in SPLASH_WIDTH/SPLASH_HEIGHT; this will make the splash screen look good on MacOS Retina screens and Windows/Linux machines with HiDPI scaling enabled. (The old "Branding"/Splash Screen panel in NetBeans doesn't really understand this new convention, though.)
