### ISSUE TITLE
try with resources formatting adding extra space

### ISSUE THREAD

**Issue by dstutz** [apache/netbeans#3720]
### Apache NetBeans version

Apache NetBeans 13

### What happened

try with resources formatting adds an extra space after the opening parens.
```
 try ( InputStream is = new FileInputStream("foo")) {
      ^   
```

Unfortunately, we use checkstyle and this causes a rule violation *and* we use format on save.

### How to reproduce

Type the following and format
`try (InputStream is = new FileInputStream("foo")) { }`

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Windows 10

### JDK

Eclipse temurin jdk-17.0.0.35-hotspot

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

This has been plaguing people on and off for several old versions.  It used to be related to the nb-javac plugin but I have tried with/without/activated/deactivated and it doesn't seem to make a difference, it keeps adding the extra space.

Some previous issues:
https://issues.apache.org/jira/browse/NETBEANS-236
https://issues.apache.org/jira/browse/NETBEANS-4641
https://issues.apache.org/jira/browse/NETBEANS-4676
https://issues.apache.org/jira/browse/NETBEANS-6129
https://issues.apache.org/jira/browse/NETBEANS-6400

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by PavelCibulka** [comment]
Same here on Netbeans 13.

It was symptom of much bigger problems related to nb-javac in previous versions. I usually fixed it by installing nb-javac plugin for second time (it uninstalled somehow).

I hope that extra space is only problem.

**Comment by ilgrosso** [comment]
Same here with NB 14, Zulu 17 on Ubuntu 20.04.
Hope it gets fixed soon.

**Comment by AndrewG10i** [comment]
Issue still present on NB 15.

**Comment by adamoutler** [comment]
This issue can be clearly seen in the Project Properties->Formatting->Category: Alignment. 
`try ( Resource r1 = null;`

The space between `(` and `Resource` cannot be removed, but oddly if one visits the Project Properties->Formatting->Category: Spaces, then selects "try", the space doubles so the result now contains two spaces between `(` and `Resource`.
`try (  Resource r1 = null;`

I'm not sure how to fix this problem, but it certainly is annoying when running tools such as CheckStyle which declare errors in your code style unless you disable the rule and/or turn off all auto-formatting.  

Has anyone found a workaround?
![Netbeans Autoformatting Error](https://cloud.adamoutler.com/index.php/apps/files_sharing/publicpreview/giLMaq7qmxMppEz?file=/autoformat.jpg&fileId=381780&x=2880&y=1620&a=true)

**Comment by neilcsmith-net** [comment]
Putting a milestone on this, and will take a look ASAP.  Be good to get this fixed in NB16 - annoying a lot of people, myself included.

**Comment by AndrewG10i** [comment]
Great news, very looking forward!

I would like to note that besides adding a space it also changes the formatting of code when several resources are used in the try-with-resources block on separate lines.

This worked well until NB 13 (e.g. in NB 12.6).

Original code:
```
try (InputStream is1 = getIsOne();
        InputStream is2 = getIsTwo();) {
    ...
} catch (IOException ex) {
    ...
}
```

After formatting both resources getting into one line:
```
try ( InputStream is1 = getIsOne();  InputStream is2 = getIsTwo();) {
    ...
} catch (IOException ex) {
    ...
}
```

Hopefully that could be also addressed within the fix for the reported issue as seems it is related.
Thank you!

**Comment by neilcsmith-net** [comment]
I think #4648 should fix the extra space if someone wants to help test.  It seems to be to do with an implicit `final` modifier. The code is currently making sure there's a space between that and the type, even if it's not in the source.  Try an explicit `final` and you won't see the problem. I assume that at some point the compiler API started reporting the source positions of that element differently.

The removed line breaks may also be due to changes in the reported token positions, but I'm stuck on that one at the moment. Will leave for another fix.  A partial workaround is setting the wrapping to always wrap on try resources.

**Comment by neilcsmith-net** [comment]
> The removed line breaks may also be due to changes in the reported token positions

That the issue remains if the explicit `final` is in, makes me think that might be a separate issue.  Have tracked to where I think it's removed at https://github.com/apache/netbeans/blob/master/java/java.source.base/src/org/netbeans/modules/java/source/save/Reformatter.java#L4713 The call to `accept()` rejects the `SEMICOLON` token.  Not had a chance to look deeper into that.

**Comment by adamoutler** [comment]
> Try an explicit `final` and you won't see the problem.

This works, but causes CheckStyle to report a different problem.
`(modifier) RedundantModifier: Redundant 'final' modifier`

I'm eagerly awaiting NB16!

**Comment by neilcsmith-net** [comment]
@adamoutler that was really meant as a demonstration of what's happening, not as a workaround.

**Comment by adamoutler** [comment]
Yes.  I can't help but try it.   However, as you mentioned, the aforementioned fix offloads the problem to explicitly declared `final` modifier.  Since the `final` modifier is implicit, a Line Warning could be used to discourage the use of declaring an explicit final when it is already implicit.  I think a Line Warning would wrap it up neatly.

**Comment by rturner-edjuster** [comment]
I just tried NetBeans 16, and this issue still exists for me. I checked the formatting settings, and I do not have a space within brackets for try statements, but it's still adding one.

**Comment by neilcsmith-net** [comment]
@rturner-edjuster I can't replicate this problem in NetBeans 17. Don't have 16 to hand to test, but not sure anything changed in this regard. Please try with a clean userdir and without importing old settings.  If it's still there, open another issue.  Also seen something odd somewhere with different behaviour of `var` but can't remember offhand where that was.

**Comment by adamoutler** [comment]
Porblem is resolved.  Thanks for your work!
