### ISSUE TITLE
Every (gradle) projects show "Unsupported Java Runtime" warning

### ISSUE THREAD

**Issue by martinmeeser** [apache/netbeans#3726]
### Apache NetBeans version

Apache NetBeans 13

### What happened

After the snap upgraded  NB to 13, all (gradle) projects show warning.

![image](https://user-images.githubusercontent.com/7906509/157123062-d7769be2-e327-4095-a4f5-073d846d9148.png)

### How to reproduce

Create gradle project

gradle 7.2, 
java 17

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Ubuntu Budgie 21

### JDK

openjdk-17

### Apache NetBeans packaging

Other

### Anything else

Installed via snap

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by lkishalmi** [comment]
That's an expected behavior. Gradle officially supports Java 17 from version 7.3.

Yes, 7.2 could mostly work, but we decided to stick with the officially supported Gradle - JDK version pairs in order to avoid some gray areas where 7.2 does not work with Java 17.

So upgrade to 7.3 or even 7.4 and your projects will work with Java 17!

**Comment by martinmeeser** [comment]
Thank you @lkishalmi , looking forward to work with NB 13
