### ISSUE TITLE
Can not open NetBeans.

### ISSUE THREAD

**Issue by lmy46** [apache/netbeans#3750]
### Apache NetBeans version

Apache NetBeans 13

### What happened

It was normal the first time it was turned on, and when he asked whether to import version 12 data, I answered yes. Then halfway through the execution, I clicked to import the 12 version of nbjava. Then he said to reopen, I restarted NetBeans. As a result, it can no longer be opened. 

Even if you uninstall it, then install it again. Can't open NetBeans normally. 

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

Windows

### JDK

Zulu 1.8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by mbien** [comment]
try removing .netbeans/13 in your user config folder and start again. This time, don't import the config from 12.x when asked during NB start.

**Comment by neilcsmith-net** [comment]
If this works, you can use `Tools / Options / Import` to bring in some or all of the configuration that you want from the earlier version. The problem may well be that installing `nbjavac` from an earlier version is causing problems - this is no longer needed as it is included in NetBeans 13.  I wonder if the change in module structure is causing the older version to be a problem.

Also -

> Zulu 1.8

JDK 11 is the minimum requirement for running NetBeans 13.

**Comment by mbien** [comment]
@neilcsmith-net I was wondering if something like this could happen again and checked if we bumped the version of nb-javac in each release since it happened the first time + tested settings migration. I didn't consider someone importing nb-javac from 5 releases ago... oh well. Would be too easy if everyone would run JDK 17 :)

**Comment by wumpz** [comment]
I had something similar. After importing the settings of an older version, somehow the installation directory of NetBeans was corrupted. For instance, suddenly the complete etc directory was missing. I could solve this by simply installing Netbeans 13 over the existing installation. I didn't have to delete some config directories.

However, since this never happened again I didn't consider creating an issue here.

**Comment by vieiro** [comment]
Closing because no response. Possible duplicate of #3782
