### ISSUE TITLE
New Entity Class from Database does not work

### ISSUE THREAD

**Issue by akaouane** [apache/netbeans#3813]
### Apache NetBeans version

Apache NetBeans 13

### What happened

When i want to add "New Entity Class from Database" and try to create a new data source, nothing is happened even if I do all things well.
So I cannot add a new Entity class.

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Ubuntu 20.04

### JDK

OpenJdk11

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by akaouane** [comment]
This issue was by using 'Payara Server 5.2022.1'.
When I added 'GlassFish Server 6.2.1', the problem does not appear and I can add entity class.

**Comment by richard-grin** [comment]
The same problem with Windows 11, Payara 2022.1, NetBeans 13.
2 problems actually:
  1. The wizard print the message "The name of the driver class for the datasource is missing". I have to modify the definition of the connection-pool in domain.xml to add the driverClass property.
  2. I restart the wizard. I cannot use an already defined connection to the database. I have to create a new one by giving another JDBC URL.

Conclusion: there is a workaround but this wizard worked well before and it does not work any longer. It is not the only problem with the support of NtBeans for Jakarta EE.

**Comment by asbachb** [comment]
@akaouane @richard-grin

Could you double check if the issue is still persistent in NetBeans 20? As the enterprise module has quite a few variants it would be quite helpful to have steps in order to reproduce the issue.

**Comment by richard-grin** [comment]
Hello @asbachb,
I have just checked.
With Payara, there is still the problem of the name of the driver but you can avoid it by adding a new additional property when you define the connection pool in Payara (driverClass=com.mysql.cj.jdbc.Driver).
For the second problem, it works better but not completely. At the beginning of the wizard, when I choose the datasource, a window "New connection wizard" pops up, even if the connection is already defined. The first time, if I give the good information for the connection wizard, it works: the tables are shown, I can choose some of them and the entities are created. 
But, latter, if I want to create a new entity from another table from the *same* datasource, it does not work: the window"New connection wizard" print the message "connection already exists" (I don't remember exactly the message). To succeed in spite of this problem, I can change the JDBC URL of the connection by adding something not significant, just to change the URL. It is a workaround but it could be better without it.

**Comment by richard-grin** [comment]
Hello Matthias,

First remark : This wizard worked well a long time ago (NetBeans 8.2; I don't remember exactly when it stopped working). At that time, we had just to give a datasource; a "connection" was not necessary. The window "New connection wizard" did not appear. I don't know why someone changed this behaviour.

1. Create a database "customer" (the name for this example) in MySQL.

2. With NetBeans 20, create a new Maven Web project for Jakarta EE10 (Java with Maven > Web Application) :

3. You need to create a datasource in Payara (or another application server) named, for example "customer". With Payara, the simplest is to run these 2 commands in asadmin of Payara (replace with your name and password in MySQL; asadmin is a file in the bin directory of the installation directory of Payara; run it) :

> create-jdbc-connection-pool --datasourceclassname com.mysql.cj.jdbc.MysqlDataSource --restype javax.sql.DataSource --property portNumber=3306:user=****:password=****:databaseName=customer:serverName=localhost:useSSL=false:allowPublicKeyRetrieval=true:driverClass=com.mysql.cj.jdbc.Driver MySQLPool
> create-jdbc-resource --connectionpoolid MySQLPool jdbc/customer

The creation of a datasource is not standardized in the application servers. I think that the 2 commands above work with GlassFish too.

4. Launch the wizard.

  - Choose the datasource created in step 3 (jdbc/cutomer).

  - A window "New Connection Wizard" appears. [**The problem is that you can't use an already defined connection.** ]

  - In this window, replace the name of the database with your name (customer for my example). The same for "User Name" and "Password". Tick "Remember password". Click on "Test Connection"; the message "Connection Succeded" is displayed. Click Next. Click Finish. The tables appear and you can choose the tables used to generate the entities.

The problem is that, if latter you want to generate other entities from the same database, you will not be able to use the same connection. When the window "New Connection Wizard" will appear, and you click "Finish", you will receive the message "Unable to add connection. Connection already exists". A workaround: modify the value of "JDBC URL" in the window "New Connection Wizard", for example by adding a new property at the end. I have tried so many JDBC URL during my tests of the wizard that I can't use this workaround any longer...

It would be good if, like in the ancient times, a datasource were enough, without using a connection. But perhaps the person that added the connection had a good reason. 

Else, just after a datasource is choosen, the user should be able to choose among the already created connections. If I remember well, this is how it worked in NetBeans 12.1. *Now the problem is that a new connection is always necessary.*

I hope my explanations will help you solve the problems with this wizard.

**Comment by matthiasblaesing** [comment]
@richard-grin @akaouane please have a look at PR #6888. Please test it. A pre built binary is available from the check page: https://github.com/apache/netbeans/actions/runs/7346039460 or directly: https://github.com/apache/netbeans/actions/runs/7346039460/artifacts/1137662244

That is not a fix every problem that exists in JPA generation, just improvements to the DB connection selection.

**Comment by richard-grin** [comment]
Sorry, Matthias, I am very busy at the moment. Il will test latter. 
With this new version, is it possible to use a connection that has already been created, without having to create a new connection every time you use this wizard?

**Comment by matthiasblaesing** [comment]
> With this new version, is it possible to use a connection that has already been created, without having to create a new connection every time you use this wizard?

That is the idea.

**Comment by akaouane** [comment]
I tried with Netbeans 20 and GlassFish 7.
The Wizard works well when I Create Entity class from Database.
But I get the same problem when I try to Create new Jsf pages from entity class.
I get the error message : "Cannot be generated because EJB Lite classes are not available on project classpath".

**Comment by matthiasblaesing** [comment]
@akaouane #6888 was targetted at NB21 and was merged into that. That release is currently being done: https://github.com/apache/netbeans/discussions/6962
