### ISSUE TITLE
Netbeans 13 Cannot add Glassfishe 6.1.0

### ISSUE THREAD

**Issue by ostermannBernd** [apache/netbeans#3826]
### Apache NetBeans version

Apache NetBeans 13

### What happened

When I try to add Glasfish server 6.1.0 I got  the folowing message:
Not a valid GlassFish Server installation
So adding this server failed. Does Netbeans 13 does not support Glassfish 6.1.0?

### How to reproduce

In Netbeasn go to Services
Select Servers
Right click to add Server
Select Glassfish Server
Clich Next
Browse to the instatlalltion location of Glassfishe 6.1.0
Then iThe message Not a valid GlassFish Server installation is shown.

### Did this work correctly in an earlier version?

No

### Operating System

Windows 10

### JDK

Tried with JDK 1.8.0 and JDK 17.0.2

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by peedeeboy** [comment]
I believe Glassfish 6.1 only supports JDK11, as per https://glassfish.org/

> Note this release requires JDK 11.

NB knows to only allow this combination, it is defined in `enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/server/config/GlassFishV6_1_0.xml`.  The error message is a bit misleading...

Running NB + Glassfish on JDK11, Glassfish 6.1 is detected by NB, can be added as a server, and starts/runs fine for me.  

N.B. Because GF6.1 is JDK11 only, you will get an error trying to start GF6.1 using `asadmin` in a terminal with JDK8 (` org/glassfish/admin/cli/AsadminMain has been compiled by a more recent version of the Java Runtime `.).
