### ISSUE TITLE
JSParser doesn't yet support optional dynamic property access

### ISSUE THREAD

**Issue by n3cr0cr0w** [apache/netbeans#4111]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

Working on some newer javascript code I noticed that the JSParser doesn't like optional dynamic property access "Expected Ident but found ["

### How to reproduce

obj?.[expr]     // optional dynamic property access

### Did this work correctly in an earlier version?

No

### Operating System

Windows 10 22H1

### JDK

15.02+7-27

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Every Time

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by Chris2011** [comment]
Afaik @matthiasblaesing alread did this with his PR: https://github.com/apache/netbeans/pull/3599. So it should be in latest 14 rc-* release. Can you please just try not the daily build but the RC of NetBeans 14?

**Comment by n3cr0cr0w** [comment]
Just tested with RC3, same issue as the nightly builds.
He(@matthiasblaesing) added a lot of the new ECMA features to the JSParser, it just looks like a sub-feature to 2020 optional chaining operator was missed.

**Comment by Chris2011** [comment]
If you look into the changed files and search for "?." or nullish like for "??" it is implemented, also tests were added. So maybe there is smth more wrong. Or there must be a hint in the file, where it says "Enable latest JS features for project". Just guessing, maybe he can say smth about this.

**Comment by matthiasblaesing** [comment]
Actually this is valid. The presented case is not yet supported by the parser.

**Comment by n3cr0cr0w** [comment]
@matthiasblaesing How can I get a copy of the 1.2-SNAPSHOT to test with?

**Comment by matthiasblaesing** [comment]
Ähm - github was quicker than I liked. The reference should have been a reference. The release of 1.1 is currently being processed by sonatype.

**Comment by matthiasblaesing** [comment]
Maven central sync is done: https://repo1.maven.org/maven2/eu/doppel-helix/netbeans/lib/graaljs-parser/1.1/graaljs-parser-1.1.jar

To test in an existing installation replace `webcommon/modules/ext/graaljs-parser-1.0.jar` with the 1.1 version (the name must be kept!).

**Comment by n3cr0cr0w** [comment]
Initial testing looks great!

Is this going to make it into NetBeans 14 or 15?

**Comment by matthiasblaesing** [comment]
15 - 14 is about to be released.

**Comment by matthiasblaesing** [comment]
I intent to merge this some time next week, if there are doubts, please raise them now.

**Comment by Chris2011** [comment]
Just wanted to understand it, due to removing of rhino and/or nashorn, graaljs is the official JS parser, right?

**Comment by matthiasblaesing** [comment]
No - not whether rhino or nashorn were ever the parser used by javascript support, but since a long time they are not. I don't know the heritage of graaljs, but either the team that build it and the NetBeans team were close or even two intersecting groups. It looks as if at some point the original graaljs parser was used in NetBeans to build the AST of the language, but then development in the JS area of NetBeans slowed while graaljs was further progressing and the to versions drifted apart. Today there are two versions of graaljs: The original one used in graalvm and the netbeans fork Jaroslav Tulach kindly created to get the NetBeans fork onto a usable license, which I took and added the necessary parser features for es.next. It seemed easier to evolve nb-graaljs in a compatible way than make the jump to the upstream graaljs.

This is all independend of javascript execution - this only effects the parsing part.
