### ISSUE TITLE
Can not attach external sources files in Maven project 

### ISSUE THREAD

**Issue by helper14** [apache/netbeans#4161]
### Apache NetBeans version

Apache NetBeans 13

### What happened

In a maven project which has dependency to another maven project the 'goto source' function (which leads to this other project) brings up some kind of decompiled(?) version of the source. The 'Attach Source' button on the right top has the proper path to the source of the foreign project already set - but it does not attach it and the 'Add Zip/Folder' button does not work neither.

### Did this work correctly in an earlier version?

No

### Operating System

Windows 10 version 10.0 running on amd64; Cp1252; en_US (nb)

### JDK

17.0.3; OpenJDK 64-Bit Server VM 17.0.3+7

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
lets say you have `project_a` which uses `project_b` as regular maven dependency.

If you open both projects in NB, you should be able to navigate directly between them. NB will automatically jump to the sources instead of opening the jar.

If `project_b` is a dependency from maven central for example, you can download the source via right click (or you jump into the jar and pres the download button from there).

no need to attach sources or anything like that.
