### ISSUE TITLE
the readme points to the wrong bug system

### ISSUE THREAD

**Issue by notzed** [apache/netbeans#4172]
### Apache NetBeans version

Apache NetBeans 13

### What happened

i.e. "Bugs should be reported to https://issues.apache.org/jira/projects/NETBEANS/issues/"

It might be helpful to link to both jira and the archive of buzilla as historical references while they're still running, as the latter doesn't show up in google or bing search very well and there's still quite a lot of information there (although many links are now dead).

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

n/a

### JDK

n/a

### Apache NetBeans packaging

Other

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
the link is already fixed via #3948, all it needs is a review and I merge :)

i am not sure about the old jira tbh. Because its probably not super useful for users, even if it causes duplicates, having a fresh report for the current version has its benefits too - but i have no hard feelings about it. Someone let me know and I add both links.

@neilcsmith-net what do you think?

**Comment by neilcsmith-net** [comment]
Old JIRA and Bugzilla are both hosted by ASF. Not sure old Bugzilla links are working - possibly some redirections would get them to.

I don't think we need anything but GitHub issue link in the readme though.

Have added a comment on the PR - may need to consider readme file included with binaries too.
