### ISSUE TITLE
Netbeans 14 freezes spuriously when r-clicking at Design View

### ISSUE THREAD

**Issue by rapastranac** [apache/netbeans#4231]
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

When editing forms, when I right-click on the form and the menu is expanded, it suddenly freezes at any of the menu items

### How to reproduce

When I right-click on the form and the menu is expanded, it suddenly freezes at any of the menu items, but it does not happens consistently. Maybe a multi-thread issue.
 

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

Windows 10

### JDK

13

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
i believe I saw that too. It happens more often if the context menu is cascaded.

Might have potentially something to do with the FlatLAF update since it added some features specific to context menus (#3983). Have to check if there is a flag for that to toggle it off for testing purposes. (or test with a different look and feel enabled)

**Comment by rapastranac** [comment]
For some reason I could not uploaded the thread dump when filing this issue.

Here it is

[threaddump-1655395630439.txt](https://github.com/apache/netbeans/files/9013393/threaddump-1655395630439.txt)

I captured it with visualvm, whose original extension is tdump. I edited the extension so I could upload it here

**Comment by wumpz** [comment]
Same here since Netbeans 14 maybe two times.

**Comment by eirikbakke** [comment]
Hmm, this problem would be very good to fix. Could either of you try to see if you could manage to reliably reproduce the bug? And perhaps take a screenshot of NetBeans in the frozen state?

It might be good to try another thread dump as well.

**Comment by cts93** [comment]
I'm using Apache NetBeans IDE 14 with this: https://draculatheme.com/netbeans

I had the same issue happen to me once I started creating and editing JFrames. Same thing: change something upon context menu (particularly the Auto Resize option) and it just freezes up everything. You have to kill NetBeans through Task Manager and open again.

I just now changed NetBeans Look and Feel theme from FlatLaf Dark to something else, checked the option "Maximize use of native look and feel". It removed that front color theme I downloaded from Dracula so I added it again and changed Look and Feel back to FlatLaf Dark. I still didn't get any freeze ever since; It seemed to have solved the problem for me.

So what we know from this is it's clearly something to do with themes, perhaps compatibility issues with custom themes.

**Comment by DevCharly** [comment]
@cts93 thanks for your report and for mentioning JFrame.

I can now reproduce it. I thought that it could be related to JFrame and played around and had a freeze.
But it turned out that it has nothing to do with JFrame.
It is related to **Preview Design**. Once showing a preview, then menus that have submenus freeze NB.

Steps to reproduce:

1. create a new form
2. click **Preview Design** button in designer toolbar, which shows an empty design preview window
3. close the design preview window
4. right-click on panel in designer shows context menu
5. move mouse down the context menu over some items that have submenus --> freeze

It is indeed related to FlatLaf submenu usability improvements: https://github.com/JFormDesigner/FlatLaf/pull/490 (used in NB 14 since PR #3983)
If I disable this feature, it does not freeze.

There are no exceptions. The stack looks OK.
ATM have no idea why it is dead 😕

**Comment by DevCharly** [comment]
Following line in NB form designer causes the problem:

https://github.com/apache/netbeans/blob/07a71662007f8f34126e7b973e29630b0152de67/java/form/src/org/netbeans/modules/form/FormLAF.java#L96

When showing a preview, the designer creates a second instance of the current L&F (either class `FlatLightLaf` or `FlatDarkLaf`) and invokes `FlatLaf.initialize()`, which installs a lot of listeners, factories, etc into the system. Then there are duplicate listeners, which cause problems. In case of FlatLaf, `initialize()` should be not invoked multiple times.

The freeze happens because there are two listeners that both temporary install event queues:

1. push first event queue (`Toolkit.getDefaultToolkit().getSystemEventQueue().push( ... )`)
2. push second event queue 
3. pop first event queue --> freeze

Will add some checks to FlatLaf to prevent duplicate execution of `FlatLaf.initialize()` ...

**Comment by cts93** [comment]
@DevCharly Whoa! I didn't know you were the creator himself. Thanks for your reply and effort into improving it for all of us.

**Comment by mbien** [comment]
@DevCharly I suppose we could disable the submenu improvements for one release in NB, so that we don't have to rush fixes into FlatLaf (no need to hurry). I had the feeling it might have something to do with it, I just couldn't reproduce the exact conditions - great job for making the connection with the form designer.

Btw when the freeze happens my entire xserver freezes. I have to ctrl+alt+F2 into shell and terminate the process to recover (cinnamon desktop environment, nv drivers).
