### ISSUE TITLE
What's New fails to load

### ISSUE THREAD

**Issue by aplatypus** [apache/netbeans#4288]
### Apache NetBeans version

Apache NetBeans 14

### What happened

* Started Netbeans v14 Start Page tab displays
* The `What's New` tab fails to load "`Error whiile loading content`" message
* `[Reload]` button produces same message as shown:

![Screenshot - `Error whiile loading content`](https://user-images.githubusercontent.com/67028/176066913-30e14f49-03eb-4809-b3a0-d70b6c19b3ef.png)

### How to reproduce

* Start Netbeans 
* The What's New area works with Netbeans v13, using the same User directory
  * If someone tells me what files/folder to grapb I can attach it here.

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

Linux version 5.15.0-39-generic running on amd64; UTF-8; en_AU (nb)

### JDK

openjdk version "18.0.1" 2022-04-19, OpenJDK Runtime Environment Zulu18.30+11-CA (build 18.0.1+10)

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

* Please see: [Add Restore operation for "Start Page" / "What's New" tab](https://github.com/apache/netbeans/issues/3910)
  *  Which documents what can be done -- Some things may be different on a new release.
  *  Perhaps the refresh button should just implement the steps in #3910 (???)

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by mbien** [comment]
what is in your `~/.netbeans/14/config/Preferences/org/netbeans/modules/welcome.properties`?

**Comment by aplatypus** [comment]
* The welcome tab works with Netbeans v13.
* I compared v13 file with v14 -- _Same_
   
![image](https://user-images.githubusercontent.com/67028/177669235-88cdce94-4ef6-4b6d-980a-ed5ca813f55b.png)

The text:
```
blogs.apache.org/netbeans/feed/entries/atom=Fri, 17 Jun 2022 16:07:02 GMT
firstTimeClose=false
lastActiveTab=2
showOnStartup=true
startCounter=3
```

**Comment by ebresie** [comment]
When upgrading to 14 did you import settings from 13 or start fresh?

**Comment by mhalachev** [comment]
I can confirm that the issue still exists in NB21. Here are the steps to reproduce and an analysis what is possibly going on.

### Steps to reproduce

1. Install next version after having NetBeans already installed. (e.g. NB21 over 20).
2. Proceed with Import Settings from previous version on first run.
3. Open Start Page and navigate to What's New.

### Expected behaviour

- News feed should load.

### Actual result

- Error while loading content is displayed  (Reload does not work).

### Workaround

1. Go to [settings directory]/config/Preferences/org/netbeans/modules/
2. Delete welcome.properties, or just delete the date from the atom feed.
3. Restart the IDE

If my understanding is correct, when settings are being imported from a previous version, `welcome.properties` is copied and it contains the date of the fetched atom feed, but the actual cached atom feed file is not copied from the old cache.

`blogs.apache.org/netbeans/feed/entries/atom=Fri, 23 Feb 2024 14:36:54 GMT` 

Let's take look at the following: https://github.com/apache/netbeans/blob/736cf60be7411e88064c83bc947f62cd6b3b76b9/nb/welcome/src/org/netbeans/modules/welcome/content/RSSFeed.java#L341-L349

The exception caught here (and the "Error while loading content" displayed) is possibly thrown by an attempt to read the atom feed from the cache file, which, as mentioned before, in this case contains no data: https://github.com/apache/netbeans/blob/736cf60be7411e88064c83bc947f62cd6b3b76b9/nb/welcome/src/org/netbeans/modules/welcome/content/RSSFeed.java#L214-L218

Checking the cache file size and/or actual content may be considered, or even removing the SAXException catch and eventually defaulting to the next one as an attempt to reload the news feed:
https://github.com/apache/netbeans/blob/736cf60be7411e88064c83bc947f62cd6b3b76b9/nb/welcome/src/org/netbeans/modules/welcome/content/RSSFeed.java#L350-L356

**Comment by mhalachev** [comment]
@mbien Please take a look at the aforementioned. Perhaps this could get in NB22...

**Comment by mbien** [comment]
@mhalachev want to give this dev build a try: https://github.com/apache/netbeans/actions/runs/8198412804/artifacts/1308149910 ?

**Comment by mhalachev** [comment]
@mbien Thanks! Tested it and can confirm that it now works as expected.

**Comment by mbien** [comment]
@mhalachev cool! thanks a lot for checking.
