### ISSUE TITLE
NetBeans 12.5 "bug"

### ISSUE THREAD

**Issue by Lucky737V** [apache/netbeans#4477]
### Apache NetBeans version

Apache NetBeans 14

### What happened

So I was following the steps from this video I found on youtube (https://youtu.be/GCgj91ifGuk), and I suppose it was going well but for some reason when I clicked the run project button it just showed me a "notifications" bar at the lower end of the screen. Well, it didn't even open the bar, a red bubble popped up near the lower right corner of the program. When I clicked it there were two notifications: the first one said I should download a library or something to optimize the performance of the program, but the second one said there was an "Unexpected Exception". And now I'm here. 

These messages I got from the logs might help.

UI log:
<param>NullPointerException at com.sun.tools.javac.jvm.Code.emitop0</param>
  <param>&lt;Please provide a description of the problem or the steps to reproduce&gt;</param>
  <param>*********</param>
</record>

IDE log:
WARNING [org.netbeans.modules.java.source.indexing.JavaIndex]: MultiPassCompileWorker caused an exception

WARNING [java.util.prefs]: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.

### How to reproduce

this is what I wrote:
Project12022.java:
package project1.pkg2022;

/**
 *
 *
 */
public class Project12022 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        System.out.println("Hello Netbeans 12.5!");

Mainframe myFrame = new MainFrame();
myFrame.init();
    }

}

Mainframe.java:

import javax.swing.JFrame;
import javax.swing.WindowConstants;

public class Mainframe extends JFrame {
    public static void init() {
setTitle("hi");
setSize(450, 300);
setDefaultCloseOperation (WindowConstants.EXIT_ON_CLOSE);
setVisible(true);
    }

}

![netbeans64_G76Hw4kiVt](https://user-images.githubusercontent.com/110802647/183347806-6f0d5b58-ead4-4a3b-9250-f597ae717d68.png)}

![netbeans64_AHp2HSY2OC](https://user-images.githubusercontent.com/110802647/183347819-d3b46965-40c5-4444-8c3c-1aa2dfa34bf4.png)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

Version 8 Update 341

### Apache NetBeans packaging

Apache NetBeans platform

### Anything else

IDK what the apache Netbeans packaging is, sorry.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
The current release would be NetBeans 14 and 15 should be out in a few weeks. It isn't very useful to report issues of older releases since firstly: they might be already fixed and secondly: if they aren't, having updated details and stack traces for the current release helps finding the issue. You probably also noticed that you couldn't select NetBeans 12.5 on this issue reporting form.

I know you only wanted to help and followed what the IDE told you to do. So maybe we should update the exception reporter to encourage the user to update instead of pushing to report bugs, once the release isn't current anymore.

**Comment by lkishalmi** [comment]
The issue is no nb-javac plugin is installed. NetBeans does not work without nb-javac on Java 8. If you see the editor closely, the syntax higlight is minimal (provided only by the Lexer), that's a sign that the Java Parsing support is missing.

Anyway, just use NetBeans 14 or 15, It comes with the requires javac infrastructure.
