### ISSUE TITLE
Import Jakarta

### ISSUE THREAD

**Issue by Corner99** [apache/netbeans#4624]
### Description

I have a problem when importing the jakarta library to my project I don't know what kind of update or library I'm missing, since I've seen that this import usually works just by having java installed
![jakarrta](https://user-images.githubusercontent.com/113322930/189565762-2b94091b-5aa6-4993-874a-8e43c967c818.png)

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
First of all: you are using NB 12.6. We are at 15 :)

`jakarta.*` packages are not part of the JDK, they are Jakarta EE. They are a dependency you have to add to your project. If you are using maven, it would be something like this for servlets: https://mvnrepository.com/artifact/jakarta.servlet/jakarta.servlet-api/6.0.0

I am going to close this since this is not really a NetBeans issue. You could ask for help on the `users@netbeans.apache.org` mailing list, issue trackers are not really a good place for help topics.
