### ISSUE TITLE
Tab's Close button not showing on partially hidden left tab

### ISSUE THREAD

**Issue by NoeGuerreroAscencio** [apache/netbeans#4738]
### Apache NetBeans version

Apache NetBeans 15

### What happened

When you have several tabs open, and they don't fit you have to scroll using the arrows, everything good until here but when you want to open that one tab that's on the left partially showing (because you have several open) the close button doesn't show up when you hover the tab, however they do close when you click when you click on them where there should be the close button showing, but they don't   show up if the tab is just partially hidden. It bothers a lot because I have close the tab several times when i wanted to work on them, sometimes you have a lot of tabs open and you need to navigate through the tabs
![captura](https://user-images.githubusercontent.com/111932452/194183025-afb3951e-f72e-4eec-a3d6-4db68183d3ea.png)

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

Windows 10

### JDK

8 update 321 compilation 1.8.0_321-b07

### Apache NetBeans packaging

Apache NetBeans platform

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
not sure how to reproduce this. The close button is rendered in my case even if only a few pixel are visible. (mouse is pointing at it, its just not on the screenshot)
![image](https://user-images.githubusercontent.com/114367/194220316-43710ef2-6275-4827-81e1-9baa37fcb992.png)

do you know that you can use the mouse wheel to navigate through the tabs instead of the arrow buttons?

**Comment by rasa-app** [comment]
I can confirm this issue. I'm using windows

**Comment by NoeGuerreroAscencio** [comment]
@mbien  maybe it's because you have a different theme and color and that's why you can't replicate it.

**Comment by mbien** [comment]
@NoeGuerreroAscencio I tested with the same theme (FlatLaf) just the dark version of it on linux. This issue might be windows specific since all reporters mentioned windows so far.

You could also try a more recent JDK, since NetBeans doesn't support JDK 8 anymore. JDK 17 would be the most recent long term release.

**Comment by NoeGuerreroAscencio** [comment]
Just updated to JDK 17 (confirmed with "java -version" through CMD), **the problem still persists**, problem might be Windows spcific just as stated in bug report.

**Comment by NoeGuerreroAscencio** [comment]
@mbien Just updated to JDK 17 (confirmed with "java -version" through CMD), **the problem still persists**, problem might be Windows specific just as stated in bug report.

**Comment by rkeen-siemens** [comment]
I have the same issue on CentOS 7.6/Gnome 3 with NetBeans 16. It's easy to reproduce:
1. Open more tabs than will fit in the width of the tab bar (or resize the window)
2. Click the right arrow button to reveal tabs to the right (not always necessary)
3. Move your mouse over the leftmost tab that is just visible

There is no close button visible, but the tooltip indicates it will close and clicking does in fact close the tab.
