### ISSUE TITLE
Netbeans 15 has no ubuntu installer?

### ISSUE THREAD

**Issue by quantrpeter** [apache/netbeans#4796]
### Apache NetBeans version

Apache NetBeans 15

### What happened

Netbeans 15 has no ubuntu installer?

### How to reproduce

Netbeans 15 has no ubuntu installer?

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

ubuntu

### JDK

18

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment]
The old Linux installer is no longer released due to a variety of unfixed issues.  Aside from the binary zip, NetBeans is available via Snap; as a DEB and an AppImage under the [community installers](https://netbeans.apache.org/download/nb15/#_community_installers); as a third-party FlatPak; and potentially in a few other ways.  Any of these are a better option!  Choose the one that works best for you.

**Comment by quantrpeter** [comment]
thx
