### ISSUE TITLE
"Help > About" doesn't show cache directory

### ISSUE THREAD

**Issue by errael** [apache/netbeans#4876]
### Apache NetBeans version

Apache NetBeans 16 release candidate

### What happened

![CacheDirNotVisible](https://user-images.githubusercontent.com/20450427/198412656-87850da7-17b4-45aa-85a3-ee1a4021e2d8.png)

Problem occurs when there are updates available. Enabling the vertical scroll bar might fix it.

### How to reproduce

In plugins need to have an update center with available updates enabled.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Linux harmony 5.19.16-76051916-generic #202210150742~1666053244~22.04~cf07008 SMP PREEMPT_DYNAMIC Tue O x86_64 x86_64 x86_64 GNU/Linux

### JDK

openjdk version "11.0.2" 2019-01-15 OpenJDK Runtime Environment 18.9 (build 11.0.2+9) OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

### Apache NetBeans packaging

Own source build

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
the vertical SB was actually intentionally disabled so that the window can size itself properly. #3660

wondering why this stops working once there is the updates notification. Maybe it appears asynchronously after the window is layed out / visible? If yes then we would have to pack the layout again on update.
