### ISSUE TITLE
Uncompilable code exception with Compile on Save 

### ISSUE THREAD

**Issue by pedro-w** [apache/netbeans#5260]
### Apache NetBeans version

Apache NetBeans 16

### What happened

Certain projects cause a runtime exception when run or debugged in the IDE, when the 'compile on save' option is selected in the project properties. One trigger is using the `instanceof` pattern matching, e.g. 
``` java
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
  if (evt.getSource() instanceof JButton button) {
    JOptionPane.showMessageDialog(this, String.format("Pressed '%s'", button.getText()));
  }
} 
```
The exception is "Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Uncompilable code" - see below for more details.
The problem does not occur if compile on save is not selected, or when running the build JAR direct from the command line.
Clean and build project does not help.
Clearing the NB cache does not help.

### How to reproduce

I've made a minimal project on github which reproduces always for me: https://github.com/pedro-w/UncompilableCodeDemo
1. Clone this project and open in the IDE
2. Run and press the button on the form that appears - should be OK
3. Close app and select 'Compile on Save' in the project properties
4. Re-run and press the button - the exception should appear

```
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Uncompilable code
	at demo.NewJFrame.jButton1ActionPerformed(NewJFrame.java:47)
	at demo.NewJFrame$1.actionPerformed(NewJFrame.java:39)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
```
...
```
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
BUILD SUCCESSFUL (total time: 4 seconds)
```

### Did this work correctly in an earlier version?

I believe it worked correctly on NetBeans 15

### Operating System

Windows 11 Pro 22H2 (x64)

### JDK

openjdk version "17.0.3" 2022-04-19 OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7) OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by pedro-w** [comment]
The only other platform I have access to is NB15 / JDK 17 on a Macintosh and that did not have this issue.

**Comment by negora** [comment]
I can confirm this issue. I've versions 15 and 16 of NetBeans IDE installed in Debian 11.6, and the latter works incorrectly when I've the option _Compile on save_ enabled (which I always have). Version 15 behaves well.

As @pedro-w mentions, in my case what triggers this error is the use of the newer form of `instanceof`, the one that uses pattern matching. All the classes that use this form are affected. I've checked this by using `javap` and decompiling them. I've found code like this:

```
#39 = Utf8               (J)I
#40 = Class              #41           // java/lang/RuntimeException
#41 = Utf8               java/lang/RuntimeException
#42 = String             #43           // Uncompilable code
#43 = Utf8               Uncompilable code
#44 = Methodref          #40.#45       // java/lang/RuntimeException."<init>":(Ljava/lang/String;)V
#45 = NameAndType        #5:#46        // "<init>":(Ljava/lang/String;)V
```

I've tested this with versions 17 and 19 of OpenJDK.

**Comment by neilcsmith-net** [comment]
Cannot reproduce the error with the shared project.  Except in the editor when first opening, because I didn't have a JDK platform registered with that name.  Are you sure an invalid platform isn't the cause?

I have to say that in general, `Compile on Save` is the first thing I switch off on any actual work projects.  Not a fan!

**Comment by pedro-w** [comment]
> Are you sure an invalid platform isn't the cause?

I'm sure it isn't. 

What OS / JDK are you using, @neilcsmith-net ?

**Comment by neilcsmith-net** [comment]
Just realised I was testing 17-rc1.  And picking up JDK 19.  This is on Ubuntu 22.04.

With JDK 17 I can replicate the error.  I have a feeling that this is due to nb-javac being based on JDK 19 and (possibly the `release` property not being configured in the project).

cc @mbien got a thought on this?

**Comment by mbien** [comment]
> cc @mbien got a thought on this?

@neilcsmith-net no thoughts. I probably haven't noticed this since am not using compile on save due to worries about issues like this here. I do not like IDEs sidelining the build with partial recompilation or other tricks - this is only asking for trouble. (only my opinion of course). Improvements in tooling like mvnd made builds really fast so I don't really feel like i am missing out on something.

**Comment by mbien** [comment]
@neilcsmith-net we can add this item to the "good defaults" thread in case we have another one for NB 18. Maybe its something we should have off by default.

**Comment by negora** [comment]
I'm not a fan of auto-compilation made by IDEs either. But I admit that it's very useful when you're debugging in NetBeans, need to make small changes to the code and don't want to do a full redeploy of your application. Does *mvnd* fit in that use case?

I've never used *mvnd*. A reason for this is that time ago, somewhere, I read that a build with Maven should be made from a fully clean state... But I guess that, during development, that's not so critical. Right? That's very different from a build aimed for production.

I'm going to temporarily disable auto-compilation in my projects and see if I can live without it. I only relied on it occasionally, so in my case I guess it won't be traumatic. What about you @pedro-w?

**Comment by pedro-w** [comment]
Personally I could live without it. I believe it is most useful if you have a very large project (which is not me). More importantly though I think it should either always work or be removed entirely. I could do some investigating if someone can point me in the right direction to start - are we saying it's probably something in `nb-javac` which I think has its own repository these days?

**Comment by neilcsmith-net** [comment]
> But I admit that it's very useful when you're debugging in NetBeans, need to make small changes to the code and don't want to do a full redeploy of your application.

Why do people think they need `Compile on Save` for that feature?!  I use `Apply code changes` all the time without it.

> are we saying it's probably something in `nb-javac` ... ?

It might be, but as that's mostly an automated backport of javac from JDK 19 to JDK 8, I'd start with how that's invoked inside the NetBeans sources when compile-on-save is active.

**Comment by negora** [comment]
> Why do people think they need Compile on Save for that feature?! I use Apply code changes all the time without it.

I may be wrong, but the times I used `Apply code changes` manually (with `Compile on save` disabled), I think it required to run a build earlier so that changes took effect. I run my applications in Wildfly Application Server, so maybe that affects the result.

**Comment by mbien** [comment]
> Does mvnd fit in that use case?

mvnd is just like maven but it has a warmed up daemon running in the background. Additionally the mvnd launcher is a native image which makes execution time of maven commands very fast while the "regular" hotspot JVM running the the background keeps as much state as possible without having to parse the pom again and again etc. Just point NetBeans to the mvnd installation instead of regular maven and most builds should "just work".

mvnd runs many tasks in parallel, which is the main reason why some projects with more exotic plugins might fail. I have seen it happening before, but since maven and mvnd are a drop-in replacement its usually not a big deal - I simply switched back on a case by case basis.

NB 17 will have some mvnd specific fixes since the maven output looks slightly different which confused the stacktrace linker and things like that.

**Comment by sroeper** [comment]
I can confirm that you get an error message:
`--- exec-maven-plugin:3.1.0:exec (default-cli) @ AssertjTest ---
Exception in thread "main" java.lang.RuntimeException: Uncompilable code`

with Compile on Save on.

Envirnoment:
Product Version: Apache NetBeans IDE 17
Java: 17.0.4; Java HotSpot(TM) 64-Bit Server VM 17.0.4+11-LTS-179
Runtime: Java(TM) SE Runtime Environment 17.0.4+11-LTS-179
System: Mac OS X version 13.2.1 running on aarch64; UTF-8; de_DE (nb)

Test Code:

```java
import java.util.Collection;

public class Main {

  static class Foo {
    Integer x;
  }

  public static void main(String[] args) {
    Foo x = new Foo();

    if (x instanceof Collection<?> col) {
      System.out.println("x is a collection");
    } else {
      System.out.println("not a collection");
    }
  }
}
```

Works without the pattern matching col variable,
I use CoS in every project and most of them are big, so CoS is an advantage especially when I write test.  It cost me hours to find that, so I would like to see that this get fixed.

**Comment by neilcsmith-net** [comment]
Had another look at this. Looking at the compilation task, not much stands out - `release` isn't set, but forcing that doesn't make things work.  Something awry in nb-javac or its invocation, but not sure what.  cc/ @jlahoda any idea what might be going on here that we could look at?

Have added a milestone and priority - this should work out of the box with default settings, which I guess @mbien might include thinking what those default settings are!

**Comment by mbien** [comment]
@neilcsmith-net its on the list of default setting tweaks in the mail I sent yesterday to the dev list after you reminded me that I haven't done that yet :)

**Comment by neilcsmith-net** [comment]
Thanks @jlahoda for opening #5682 which should resolve this issue.

@mbien I still think it's worth considering CoS off by default (and particularly off when there's no nb-configuration.xml file). We have a bunch of UI things that mention CoS, and there's a useful warning message when enabling.

**Comment by mbien** [comment]
@neilcsmith-net agreed. The proposal is to turn it off by default for new maven projects.

**Comment by mbien** [comment]
@neilcsmith-net we can turn it off for everything and make the user fill out a captcha to reactivate it :P

what I am saying is that the [mail is already out](https://lists.apache.org/thread/rdflfdbt2v0cxz9mk198tonm0hnff1bg) and open for discussion. Feel free to suggest more items or comment on existing items. We probably should just turn it off in general without too many checks and conditions.

**Comment by mbien** [comment]
@negora assuming everyone agrees with it, this would only result in a change to the default settings. It would not remove the feature from NetBeans. If the feature worked well for you before, it will continue to do so.

I can't really answer the question about prioritization since I can only speak for myself, but I don't think anything will change there either. NetBeans is run by the community, so as long someone is interested in this feature there will be probably someone who is also willing to update it.

**Comment by negora** [comment]
@mbien Cool. Although I'm trying to program without this feature in 2 of my projects (just as an experiment), I feared that it were relegated after this change. Thank you.

**Comment by tudogeorge** [comment]
In my case it was an issue with my project setup, just that I didn't get a more helpful message than the "Uncompilable code" runtime exception thrown when invoking that specific part.
I got this while working on an application with lots of modules; the application with its library projects is on ant.
Turns out one of the modules my application was loading at runtime in the modulepath was missing several modules it required, from its libraries.
Having so many modules, it was easier for me to add a main class to that library, try to run it and I got the missing modules in the run output.
