### ISSUE TITLE
Support New URN in Faces 4.0 Facelets

### ISSUE THREAD

**Issue by hantsy** [apache/netbeans#6069]
### Description

Faces 4.0 Faceslet use short URN instead of traditional URL, eg.

```xml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="jakarta.faces.facelets"
                xmlns:f="jakarta.faces.core"
                xmlns:h="jakarta.faces.html"
                xmlns:jsf="jakarta.faces">


</ui:composition>
``` 

All these URN based tags are not recognized by NetBeans now, there is no completion and validation for the xhtml codes.

### Are you willing to submit a pull request?

No

**Comment by asbachb** [comment]
More context: https://github.com/jakartaee/faces/issues/1553

**Comment by asbachb** [comment]
I had an initial look into the issue.

I already have a branch which adds the correct namespaces when creating new jsf pages and shows tag suggestions when using `Shift + Space`.

My concern is that the information for these suggestions are based (at least for maven projects) from a bundles JSF 2.2 taglib jar.  Which seems to be used for all jsf versions.
I guess the main problem is that the taglib.xml (which is used to generate the autosuggestions) are not part of the faces-api itself. They seem to be bundled with the implementation. So in order to show any suggestions a implementation needs to be provided somehow - which is a little bit weird as the tags are defined in the faces spec, so I don't see the point not providing them within the faces-api.jar

Currently I don't see an easy option to fetch the taglib matching the used faces version in your project. So we only show JSF 2.2 taglib information and we need to manually map the namespaces somehow based on the used faces version of the project.

/cc @mbien

**Comment by asbachb** [comment]
New PR: #6160
