### ISSUE TITLE
Blank Screen / White Screen with java logo

### ISSUE THREAD

**Issue by Matthew-Gallardo** [apache/netbeans#6093]
### Apache NetBeans version

Apache NetBeans 18

### What happened

Whenever I open the app, the blank screen only shows. I tried restarting , closing in task manager. First the loading screen shows and it will not progress. After opening it again, the white screen with logo of java will only shows.  

![image](https://github.com/apache/netbeans/assets/106909575/039d3167-60f0-4487-a52e-e1778ec45d5e)
![image](https://github.com/apache/netbeans/assets/106909575/b740b89f-33dc-45ac-a89d-794a6f52f9db)

### How to reproduce

Whenever I open the app , atleast two times it will show up

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

JDK 17.0.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

**Comment by neilcsmith-net** [comment]
Please try updating your JDK - either to 17.0.7, or JDK 20. Or try the community installers from Codelerity (linked from https://netbeans.apache.org/download/nb18/#_community_installers ) which have a bundled local JDK 20 runtime.  Let's rule out JDK issues.

Also check for the logs under `<AppData>\NetBeans\18\var\log`, see if there's any useful / interesting information when it fails, and post the log back here.

Also, if you imported data from an earlier install, try deleting the folder under `<AppData>\NetBeans\18` as well as the cache folder under `<Local AppData>\NetBeans\Cache`.

For more on the userdir and cachedir locations (since I guess you can't get to the About dialog!) see 
https://github.com/apache/netbeans/blob/master/nb/ide.launcher/netbeans.conf#L21

**Comment by Matthew-Gallardo** [comment]
**Thanks It is working fine now** 
Fixed by :
Updating JDK -- _JDK 20_
Deleting cache folder under

```
 \Users\AppData\Local\NetBeans\Caches\NetBeansVersion
```
and Roaming folder under  
``` 
\Users\Administrator\AppData\Roaming\NetBeans\NetBeansVersion
```
