### ISSUE TITLE
Hidpi scaling under Wayland with flatpak

### ISSUE THREAD

**Issue by bjoern-tantau** [apache/netbeans#6121]
### Apache NetBeans version

Apache NetBeans 18

### What happened

When launching the flatpak version of NetBeans on KDE-Plasma 5.27.5 with Wayland in 4k resolution with 2x scaling everything is really tiny.

![Screenshot_20230626_083208](https://github.com/apache/netbeans/assets/8307357/285f235e-ac29-4c15-a69d-14ab8384698f)

This might be related to #4889 but the flatpak uses Java 11.

A workaround is to add `-J-Dsun.java2d.uiScale=2` to the startup options in `/var/lib/flatpak/app/org.apache.netbeans/current/active/files/netbeans/etc/netbeans.conf`.

### How to reproduce

1. Set scaling to 200 % in KDE display settings.
2. `flatpak run org.apache.netbeans`

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

openSUSE Tumbleweed 20230604

### JDK

flatpak's OpenJDK 64-Bit Server VM 11.0.19+7

### Apache NetBeans packaging

Other

### Are you willing to submit a pull request?

No

**Comment by bjoern-tantau** [comment]
Forgot to add, it works with non-flatpak version as expected.

**Comment by neilcsmith-net** [comment]
> Forgot to add, it works with non-flatpak version as expected.

Please report upstream.  https://github.com/flathub/org.apache.netbeans/issues  The flatpak is produced by a third-party.  If the problem cannot be replicated with ASF packages then they need to work out why.  That, of course, _may_ lead to things that could be changed here, in which case an issue / PR can then be opened as necessary once the problem is understood.
