### ISSUE TITLE
netbeans 18 do not refresh vaadin/spring boot application when saving class

### ISSUE THREAD

**Issue by insastrasbge1** [apache/netbeans#6141]
### Apache NetBeans version

Apache NetBeans 18

### What happened

In netbeans 17, when saving a changed class in a vaadin/spring boot project, the application and the browser is automatically refreshed
In netbeans 18 there is no more automatic refresh. I have to stop then start again the application.

### How to reproduce

1- download basic vaadin application in https://vaadin.com/docs/latest/guide/quick-start
2- unzip and open in netbeans (this is a maven project)
3- Run class com.example.application.Application
  --> A very simple "say hello" web application should open in browser (mine is firefox)
4- Edit class com.example.application.views.main.MainView
5- add line this.add(new H1("basic change")); as first line of constructor : 
    public MainView() {
        this.add(new H1("basic change222"));
        name = new TextField("Your name");
        ...
6- save Mainview class

--> In netbeans 17, saving the class triggers a refresh in the embeded webserver (tomcat) and the browser (firefox)
--> in netbeans 18, nothing happens

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

windows 10 ; windows 11

### JDK

openJDK 20

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
Have you turned on Compile on Save in the project? This now defaults to off for new projects.

**Comment by insastrasbge1** [comment]
thank you for your prompt reply.
That was indeed the problem.
Sorry for the inconvenience, but this kind of change in default behavior is difficult for the user to diagnose.

**Comment by neilcsmith-net** [comment]
All changes in default behaviour cause some confusion, but sometimes the defaults need to change because they're _more_ problematic.  See #5826 for introduction of this change.  It is included in the release notes, although we recognise that work still needs to be done to improve release notes in general, and highlighting changes like this.

The key thing is that Compile on Save brings other issues with it, some of which are highlighted in the dialog when you enable it.  If you can find a workflow that doesn't rely on it, I would.
