### ISSUE TITLE
Reload POM action not working on maven projects

### ISSUE THREAD

**Issue by albilu** [apache/netbeans#6223]
### Apache NetBeans version

Apache NetBeans 18

### What happened

Reload POM action on a maven project doesn't work.

### How to reproduce

1. Add a new dependency on a maven project
2. Reload POM to prime project doesn't work

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Linux/Windows

### JDK

JDK 17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Project is marked with Resolve Project Problems
Project Problems Resolve action prime the project.
But Reload POM is more straightforward

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
I'm not sure Reload POM is meant to handle that case - you can just clean and build the project from that menu.

cc/ @mbien @sdedic ?

**Comment by mbien** [comment]
i build projects after adding dependencies which aren't in the local repo yet since it is the most natural way to let maven resolve the dependencies which is a completely IDE independent process.

Reloading a pom will resolve dependencies too, but this is an implementation detail and is done by NetBeans due to other reasons. You might have more luck with NB 19 since it had fixes in that area. But again: reloading a pom shouldn't be the first choice after adding dependencies. RC1 is a bit broken in that area, you would have to wait for RC2 or test a dev build of that PR: https://github.com/apache/netbeans/actions/runs/5600090492 (scroll down)

**Comment by albilu** [comment]
@mbien Here is the problem:

1. I am writting code and want to use org.json.JSONObject
2. I write the instruction: JSONObject JSONObject = new JSONObject();
3. File is now in error
4. Alt+Enter -> Search Dependencies and Add it to the pom
5. File still in error
6. If run Build the build **wil just failed even if it resolve the dependency**


A better approch is to be able to quickly run priming to resolve the dependencies. Wich i though Reload POM was there for. 
At least it the case in IntelliJ.

**Comment by albilu** [comment]
No its à simple project. The build failed because there will not be the import org.json.Jsonobject; in the file yet unless you add it manuellement as the library is not in the classpath yet.

You should be able to reproduce this easily. I will maybe record à video to show.

**Comment by asbachb** [comment]
@albilu can you share an example project?

**Comment by albilu** [comment]
https://github.com/apache/netbeans/assets/35330562/5b111225-c089-4ff6-a96d-f24953d861dc

After adding a new dependency using the quick fix action an immediate build will fail because the file is in error.
Build will only be successful after import statement for org.json.* have been added to the file(with is not automatically possible before the pom reload. unless you know the complete import statement by heart and add it manually)

This is where Reload POM action is useful as it will just prime the project(download the new dependency without failing and annoying the user). This is the case in IntelliJ.
[reloadpom.tar.gz](https://github.com/apache/netbeans/files/12175040/reloadpom.tar.gz)

**Comment by mbien** [comment]
@albilu thanks for the demo. I am not 100% convinced that this is a problem though. Yes the compilation step will fail but before attempting to compile, maven will download all dependencies which aren't there yet. That is also the reason why you can import the class right after you built - since it can be resolved.

what you essentially want is something like:
`mvn dependency:go-offline`
which will download everything so that subsequent builds can be offline.

or via UI:
![image](https://github.com/apache/netbeans/assets/114367/cdfe283a-1fe5-45c8-b2d1-f95b74ecf73d)



The fact that reloading the pom is downloading dependencies is an implementation detail. NetBeans is going to do that in a non-standard way - it is always better to let maven handle the build.

**Comment by asbachb** [comment]
Actually I don't get the expectation fully: The failing build shown in the demo is caused by the missing import, not because the dependency is not present or the project needs to be reloaded.

From my understanding when you add a dependency it's added to you pom, downloaded automatically (at least with my configuration) and after it's downloaded you're able to add the import.

I guess there's an argument if that added maven dependency also triggers the auto import feature, but not yet sure if this would be a good solution.

**Comment by albilu** [comment]
> From my understanding when you add a dependency it's added to you pom, downloaded automatically (at least with my configuration) and after it's downloaded you're able to add the import.

It weird i did some further cases after your claim and it automatically download indeed in some cases but in other cases it doesn't don't know why.

Anyway it is not really a big deal i think this issue can be closed!
Thanks

**Comment by mbien** [comment]
cool. btw I am glad to see that someone is actually using the class name search. Since it didn't work for quite some time but got fixed over the last few releases.

NB 19 will also restore some functionality there, e.g #5984
