### ISSUE TITLE
Java 11 or newer required (But on my working Laptop I can use only Java 8)

### ISSUE THREAD

**Issue by KatAlive** [apache/netbeans#6540]
### Apache NetBeans version

Apache NetBeans 19

### What happened

On previous NETBEANS versions (I'm actually using NETBEANS IDE 18) I could work also using Latest version of Java 8.
Now, with NETBEANS 19 we can't work. It says that we need Java 11 or newer to run IDE.
![Java11required](https://github.com/apache/netbeans/assets/60010244/01ec4f6e-181a-4199-8aee-3d57be943812)

### How to reproduce

Just install NETBEANS 19 on computer with Java 8 installed and latest JDK 1.8.0_202

### Did this work correctly in an earlier version?

Apache NetBeans 18

### Operating System

Windows10 Enterprise

### JDK

1.8.0_202

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
NetBeans has officially required JDK 11 since NetBeans 13.  This was made more explicit in NetBeans 19 as more things will break hard on JDK 8.

You need to run NetBeans on a more recent JDK.  That does not stop you developing projects with JDK 8 installed on the computer.

If you need a version of NetBeans with a localised JDK that does not rely on the system installed one, try the community installers instead.

**Comment by lalo-mx** [comment]
BTW you don´t have to install Java you can download the JDK as a ZIP and configure Netbeans to use it without installing it.
