### ISSUE TITLE
PHP: Ctrl + hover - freezing Netbeans (go to declaration)

### ISSUE THREAD

**Issue by Eugene-Melbourne** [apache/netbeans#6634]
### Apache NetBeans version

Apache NetBeans 19

### What happened

I get methods header definition when I `Ctrl + hover` with mouse across a methods name in form of a tooltip.
Often, when I try doing it freezes the whole NetBeans and causes CPU use spikes up to 100% that can last for half a minute.

It is not functional in this form. Please, let me know how can I disable this feature until it is fixed.

### How to reproduce

I have a large PHP project where I use a lot of third party packages, I guess it means that the project should be big.
The freezing is not happening every time, but it happens very often.
The important part is that you need to move mouse when pressed ctrl, if you first position a mouse and then just press ctrl - it will do "go to declaration". It is different and it is working fine.

### Did this work correctly in an earlier version?

I have the same negative experience with all of the known versions of NetBeans as far as I can remember, 17/18/19...

### Operating System

Windows 10 version 10.0 running on amd64; UTF-8; en_AU (nb)

### JDK

19.0.1; Java HotSpot(TM) 64-Bit Server VM 19.0.1+10-21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

I have a pretty good computer I7 with 32 GB of RAM. I don't believe scanning source texts would make this computer freeze even for one second unless there is a bug somewhere.

Please, let me know how can I disable this feature until it is fixed. Thank you

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
JDK 19 was a short term release and is end of life. You could try JDK 11 or 17 which are both long term support releases (NetBeans 20 will also support JDK 21 with is the latest LTS release). If you don't want to update the JDK all the time, NB is also available as bundle containing the latest supported JDK on the download page.

This might not help your issue, but at least the runtime is up to date :)

**Comment by Eugene-Melbourne** [comment]
Downgrade a JDK is a hack. I cannot afford breaking my environment experimenting with it at the moment. 
JDK 21 is a Release Candidate just yet.

I think it is vital to have an option to disable this feature somewhere in the
Tools > Options > Keymap
or
Tools > Options > Editor > Code Completion

It is especially confusing that in the KeyMap we have "Wheel up" and "Wheel down" but we don't have "Right Click" and "Left Click". It looks like overlook to me

**Comment by Eugene-Melbourne** [comment]
I just updated my Java to Java: 19.0.2; Java HotSpot(TM) 64-Bit Server VM 19.0.2+7-44
It still freezes the same way.

**Comment by Eugene-Melbourne** [comment]
There is another situation, that (I believe) is cause by this lack of a way to disable this feature.

<ctrl> + e - is a hotkey to delete a line of code, it is a light weight task, but when I press <ctrl> it activates the whole caboodle of functions related to mouse position such as - form a tooltip to turn and turning a text into a link.

So it freezes the whole system again for no reason, making combinations like (<ctrl> + e) vey annoying and even useless depending on where you mouse is resting at that moment of time.

I vividly remember having this "<ctrl> + e" issue on my previous work, which was more than 5 years ago. 
It means that this issue cannot be fixed by installing older version of Java, version 17 is just 2 years old.
And It also means that this issue is coming from some legacy code. I remember there was a developer version back then that supported php7 and I used it because Netbeans 8 did not support php7.

**Comment by terax6669** [comment]
![image](https://github.com/apache/netbeans/assets/19204073/2e15d179-f281-4dea-b23d-0dd5d8d3f6c2)

Yep, it has been an issue pretty much ever since I can remember (8.2 or 9), same with ctrl+space and ctrl+click. The infinite "background scanning" is gone, but the issue is not.

Excluding as many files from the project as you can as well as increasing the default cache/heap sizes used to help, but that's obviously only hiding the underlying issue... and nowadays I can't really tell the difference between increased cache size or not. Perhaps my current main project's size is just too large for it to make a difference anymore.

Personally I've gotten somewhat used to finding the class I need in the tab bar and using ctrl+f rather than ctrl+click, it's infinitely faster. And thanks to windows' win+v clipboard history I don't have to worry about copying the method name that I want to find :sweat_smile:....

The sad fact is - if you want to work on big projects you gotta switch to PHP Storm. There have been bug reports, stack overflow threads, wiki articles (now available only on web archive due to the apache overtake) and no fix for 10 years.

**Comment by junichi11** [comment]
It would be nice if someone could provide an example project to reproduce it. That way, we can investigate it. Thanks.

**Comment by terax6669** [comment]
@junichi11 
The project I'm working on isn't public, but I'm willing to send you a zip privately if you provide a way of contacting you directly.

**Comment by junichi11** [comment]
@terax6669 You can find my e-mail in my commits. e.g. https://patch-diff.githubusercontent.com/raw/apache/netbeans/pull/6437.patch

**Comment by junichi11** [comment]
@terax6669 Thank you for providing it. I'll have a look at it later but I can't promise anything about resolving this.

**Comment by mbien** [comment]
is this a duplicate of #3933?

**Comment by terax6669** [comment]
Exactly the same as I described. I even sent junichi a similar video where the go to declaration fails for 2 minutes lol

**Comment by haidubogdan** [comment]
I had the same issue recently, very lengthy processing of declaration finder and had JDK 17 on Windows.
Everything worked normally one week ago.

For the moment a quick fix was to uninstall my custom plugin **blade-php** .

So there is a possibility that it is OS related + third party plugin compatibility.

**Comment by terax6669** [comment]
I don't use the blade plugin, but I'm also on Windows

**Comment by Eugene-Melbourne** [comment]
The root cause here is maybe similar to the https://github.com/apache/netbeans/issues/3933 ( @mbien )
But it may be different because 〈Go to Declaration〉is a part of the mouse-right-click drop down menu, and it is also can be called with 〈Ctrl+B〉. 
Neither of these ever freezes my system.
Only 〈Ctrl + hover〉 causing the freezing.
The〈ctrl + mouse click〉is difficult separate from 〈Ctrl + hover〉but I'm convinced that 〈ctrl+mouse click〉is not causing it either.

I believe that the **methods header definition in a form of a tooltip** is a cause for freezing.

And I understand that it may be not even a bug, but a slowness. 
I try do avoid the word "bug" to not being judgmental. 
I call it an "overlook". 
So I believe there is a big overlook in the system that **methods header definition tooltip** cannot be disabled in the configuration.
Thus, I team up with @terax6669 in understanding that big projects can require a different treatment and developers should have a way to configure the IDE for it. There are many ways to get to the method declaration. But it is extremely unpleasant to have a feature in the IDE that can cause freezing but cannot be disabled. It is unpleasant to move a mouse away from the code field every time when you try to press 〈Ctrl+E〉. 

It is an UX problem.

I use blade and Windows ( @haidubogdan  ), but I cannot uninstall it.

**Comment by terax6669** [comment]
I disagree about calling it a UX issue. The tooltip should show immediately. I have 32 gigabytes of ram, there's no reason for it to not be cached and ready to display in a fraction of a second. Same goes for ctrl+space. IMO this is clearly related to caching code metadata and/or resolving.

Even worse you'd think that this problem would only occur once and once it's loaded to memory the IDE would be working normally, but instead if you try to execute the ctrl+click workflow on the same method a few times it will freeze again, and again... but not always. If the required data is indeed cached then it must be purged after mere seconds.

I will admit that I found ctrl+b to be more reliable, but not necessarily faster. I feel like it completes successfully more often than ctrl+click, while the latter tends to just abort multiple times.

There are issues with autocomplete and refactoring as well that would be explained by NetBeans failing to resolve some metadata, however I refrain from mentioning this too often, because I believe there's a common underlying issue. If this ever gets resolved and other features still struggle to execute properly then I will make dedicated bug _reports._

**Comment by junichi11** [comment]
I'm working on this. Maybe, I can improve this. @terax6669 's project was so helpful. Thank you!

**Comment by junichi11** [comment]
I've fixed in #6712 
Could someone test it? 
zip dev version is available: https://github.com/apache/netbeans/suites/18271218545/artifacts/1056392947

**Comment by haidubogdan** [comment]
Just to clarify "freeze" is used in the term as  **netbeans** is no longer operable and you need to force close the application [Ctrl-Alt-Delete] ?

If this is the case then it is not just a performance issue.
I've never faced such a issue so far, but I did manage to always fully "freeze" netbeans with a custom php plugin which used to embed php code (when typing or deleting  ":" chars).

If it's a performance issue then we can look at junichi11 commits or request an improvement on the indexing process in netbeans.

**Comment by terax6669** [comment]
@haidubogdan By "freeze" we mean UI becomes unresponsive. There's a video in #3933 showing the issue.

@junichi11 It seems to resolve the freezes when pressing `ctrl`, it's back to normal levels of NetBeans slowness. Down from unusable to few second wait time.

https://github.com/apache/netbeans/assets/19204073/2142c300-525e-4a96-acb5-341e5657e36f

Go to now seems to take exactly the same amount of time as `ctrl+hover` would. Going to `$protoEntry->identifier` still takes about 4 seconds, no matter how many times I try it, so there's still room for improvement.

Holding `ctrl` and moving the cursor between things doesn't always update the tooltip, as seen on video.

Those are probably not related to the freeze bug though.

The big issue is... I am no longer able to refactor.
![image](https://github.com/apache/netbeans/assets/19204073/db97862e-307b-4b1b-9942-c2f942889b2f)
Is there a 20-rc4 artifact I can download somewhere for comparison? Refactoring works on NetBeans 18.

**Comment by mbien** [comment]
> Is there a 20-rc4 artifact I can download somewhere for comparison?

-> https://github.com/apache/netbeans/discussions/6581

**Comment by junichi11** [comment]
I'm going to merge #6712 tomorrow.
Then, I will
- close this
- delete dev build
Thanks!

**Comment by Eugene-Melbourne** [comment]
Thank you very much
