### ISSUE TITLE
NetBeans Crashes with MacOS Sonoma 14.0/1

### ISSUE THREAD

**Issue by ShadowM0nkey** [apache/netbeans#6647]
### Apache NetBeans version

Apache NetBeans 19

### What happened

NetBeans immediately crashes on M1 Mac running Sonoma 14.0/1:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               java [20838]
Path:                  /usr/local/Cellar/openjdk/21.0.1/libexec/openjdk.jdk/Contents/Home/bin/java
Identifier:            java
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        bash [20603]
Responsible:           netbeans [20602]
User ID:               506

Date/Time:             2023-10-31 09:33:23.5979 -0700
OS Version:            macOS 14.1 (23B74)
Report Version:        12
Bridge OS Version:     8.1 (21P1069)
Anonymous UUID:        2752008D-E126-8BD7-F59C-84663233EF02

Time Awake Since Boot: 7700 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000000002c
Exception Codes:       0x0000000000000001, 0x000000000000002c

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   java [20838]

VM Region Info: 0x2c is not in any region.  Bytes before following region: 140737487110100
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      shared memory            7fffffed0000-7fffffed1000 [    4K] r-x/r-x SM=SHM  

Application Specific Information:
References to Carbon menus are disallowed with AppKit menu system (see rdar://101002625). Use instances of NSMenu and NSMenuItem directly instead.

### How to reproduce

Upgrade M1 MacBook to Sonoma 14.0 or 14.1. 

Launch NetBeans

### Did this work correctly in an earlier version?

Apache NetBeans 19

### Operating System

MacOS Sonoma 14.0 or 14.1

### JDK

openjdk version "21.0.1" 2023-10-17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Similar error reported with JMeter & VisualVM:

https://github.com/apache/jmeter/issues/6083
https://github.com/oracle/visualvm/issues/528

### Are you willing to submit a pull request?

Yes

**Comment by mbien** [comment]
comments on the linked issues indicate that this seems to be JDK distribution dependent. What JDK are you using and have you tried a different vendor? You can also attach the log file which has environment information in it.

the NB 20 release candidates use the latest version of FlatLaf: https://github.com/apache/netbeans/discussions/6581, although I don't remember reading anything about the menu system in the changelog, wouldn't hurt to give it a try.

**Comment by ShadowM0nkey** [comment]
@mbien You were correct. I ended up deleting the openjdk@21 version installed by HomeBrew and manually installed Amazon Corretto 21 and Netbeans now starts. Many thanks!

**Comment by philip-lourandos-sgits** [comment]
I am seeing something similar with:

- Macbook Pro m2
- 14.5 (23F79)
- Netbeans 22
- openjdk 22.0.1 2024-04-16

Netbeans 19 and 20 are fine. Saw the same issue with netbeans 21

**Comment by gtsh** [comment]
@philip-lourandos-sgits So I'm not mistaken, the problem is real, and not an 'only me' one. I'm still a bit unsure, whether we are looking at exactly the same problem as the original poster, because he, at least, had a heapdump, and he crashed immediately. 

Some quick questions:
- did you install Jdk and Netbeans from archives, or did you use homebrew?
- have you been able to generate a heapdump, or any meaningful log?

**Comment by philip-lourandos-sgits** [comment]
> @philip-lourandos-sgits So I'm not mistaken, the problem is real, and not an 'only me' one. I'm still a bit unsure, whether we are looking at exactly the same problem as the original poster, because he, at least, had a heapdump, and he crashed immediately.
> 
> Some quick questions:
> 
>     * did you install Jdk and Netbeans from archives, or did you use homebrew?

sdkman for the JDK. Downloaded zip file for netbeans from apache

> 
>     * have you been able to generate a heapdump, or any meaningful log?

Not as yet.

**Comment by neilcsmith-net** [comment]
Can you replicate with the pkg installer, or ideally the community pkg installer with internal JDK?  Those are correctly deep signed and notarized, including the bundled JDK in the community installer.  They also are app bundles with a swift launcher.  Be good to know if this is specific to unsigned bundles, unsigned native binaries, etc.

**Comment by philip-lourandos-sgits** [comment]
Using the pkg file from netbeans.apache.org yielded the same result. Using the homebrew version appears to be stable

**Comment by gtsh** [comment]
For about a week, it looked like it could be exactly the other way around for me, but no. The Problem seems to be elusive.
It happened particularly often, when I started to install or activate some plugins, not _during_ installation, but when still clicking around to select things.

And again, with the same message on sysout/err:

** Success! found: /Users/foo.bar/Library/Application Support/NetBeans/22/modules/ext/server-cert-keystore.jks
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.netbeans.TopSecurityManager (file:/Applications/Apache%20NetBeans.app/Contents/Resources/netbeans/platform/lib/boot.jar)
WARNING: Please consider reporting this to the maintainers of org.netbeans.TopSecurityManager
WARNING: System::setSecurityManager will be removed in a future release
2024-06-15 12:34:44.320 java[95131:3714403] *** WARNING: References to Carbon menus are disallowed with AppKit menu system on macOS 14 and newer. Use instances of NSMenu and NSMenuItem directly instead. See https://developer.apple.com/documentation/macos-release-notes/appkit-release-notes-for-macos-14#Menus
*** created X3DPaletteActions()
2024-06-15 12:57:15.175 java[95131:3714403] +[NSXPCSharedListener endpointForReply:withListenerName:replyErrorCode:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted
2024-06-15 12:57:15.176 java[95131:3714403] HIToolbox: received notification of WindowServer event port death.
2024-06-15 12:57:15.176 java[95131:3714403] port matched the WindowServer port created in BindCGSToRunLoop
----
[logdump_2024-06-15-13-08.zip](https://github.com/user-attachments/files/15846636/logdump_2024-06-15-13-08.zip)

**Comment by dyorgio** [comment]
Same problem here.
NetBeans 22 sometimes freeze and restart Finder (macOS shell) always during a Menu access or PopUp.
Sonoma 14.5
Azul Zulu 21 JDK

**Comment by ChMThiel** [comment]
Same problem here:
Product Version: Apache NetBeans IDE 22
Java: 22.0.1; OpenJDK 64-Bit Server VM 22.0.1 
Runtime: OpenJDK Runtime Environment 22.0.1
(installed by Homebrew)

System: Mac OS X version 14.5 running on aarch64; UTF-8; de_DE (nb)

Pleas open a new issue...it seems there are a lot of people having that problem

**Comment by neilcsmith-net** [comment]
> Pleas open a new issue...it seems there are a lot of people having that problem

Why ask others to do what you can do yourself??  Please open a new issue with the information required to do so.  Also please check if you can replicate with the community installers as that's using a known JDK signed along with the IDE.

**Comment by ChMThiel** [comment]
> > Pleas open a new issue...it seems there are a lot of people having that problem
> 
> Why ask others to do what you can do yourself?? Please open a new issue with the information required to do so. Also please check if you can replicate with the community installers as that's using a known JDK signed along with the IDE.

@neilcsmith-net you asked the same question to @gtsh and he told you that it makes no difference, how he installed netbeans. And he already suggested to move this to a new issue...

**Comment by neilcsmith-net** [comment]
@ChMThiel actually, it wasn't the same question, and he didn't check this (at least in the comments and logs above).  Let's move this over to the new issue.  Thanks for opening.
