### ISSUE TITLE
Add {@inheritDoc} to javadoc comments when `@Override` annotation exists in generated code

### ISSUE THREAD

**Issue by PavelTurk** [apache/netbeans#6718]
### Description

I suggest to add `{@inheritDoc}` inline tag whenever code generated by NB contains `@Override` method. 

For example, we have `A` class:

```
public class A {

    /**
     * Does it.
     *
     * Does it as no one else.
     *
     * @param foo
     * @return string if everything is ok.
     */
    public String doIt(int foo) {
        return null;
    }
}
```
Now we want to override `doIt` method in `B` class. So,

```
public class B extends A {

   //here Alt+Insert -> Override method -> select doIt. The following code must be generated:

    /**
     * {@inheritDoc}
     */
    @Override
    public String doIt(int a) {
        return super.doIt(a);
    }
}
```
The same is for interfaces implementations.

### Use case/motivation

In most cases Javadoc comments are provided in interfaces or parent classes while implementation and child classes take these comments from interfaces or parent classes.

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
I am not sure about this. Probably 90% of all methods I override shouldn't even have javadoc since there are non public or internal, inner classes for example, where the impl it not exposed while the super class or interface is - it would only cause noise.

Adding `inheritDoc` by default over every `@Override` will likely also cause problems when project dependencies are overwritten since the javadoc tool requires access to the full dependency source tree to be able to inherit javadoc.

There is a reason the javadoc tool does not inherit doc by default and requires the inheritDoc tag, I think IDEs should also not add this tag blindly. It is a manual step for specific situations.

**Comment by neilcsmith-net** [comment]
I agree with @mbien , many cases will not be exposed.  And having `{@inheritDoc}` inserted _without_ additional text seems like an antipattern to me.  What's the point?  Doesn't adding this also stop the automatic inheritance of docs for param and return in the example?

**Comment by lahodaj** [comment]
I incline to what @mbien, but I would like to ask more about the motivation - what's the purpose? My understanding is that if a method overrides a method from a supertype, and has no javadoc comment whatsoever, the javadoc text from the supertype's method is used automatically. I just tried, and it worked for me. So, what's the goal of trying to add `{@inheritDoc}`?
