### ISSUE TITLE
mavenindex should be by URL not by id

### ISSUE THREAD

**Issue by hylkevds** [apache/netbeans#6753]
### Apache NetBeans version

Apache NetBeans 19

### What happened

While investigating where my disk space went on an older machine I noticed the netbeans mavenindex was 17GB large. Investigating further I noticed there were several copies of the Maven Central index, each more than 6GB

The problem is that everybody that distributes a pom file can give maven central a new id, and netbeans will happily re-download the index under this new id.

Of course the real key, that determines if a repository is new or not, is the URL, not the arbitrary id defined in some random pom.xml file. Hence it would make more sense to the (normalised, hashed?) URL for the mavenindex entry.

### How to reproduce

Create a project and add repositories section witch gives Maven Central a new id. For example:
```
    <repositories>
        <repository>
            <id>Maven Central</id>
            <url>https://repo1.maven.org/maven2/</url>
        </repository>
    </repositories>
```
Given enough time the size of each will grow.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Linux Mint

### JDK

OpenJDK 17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Size of the various duplicates can grow quickly or slowly depending on the use of the projects.

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
I can't reproduce this unfortunately. I have now central2 and central3 in settings.xml and central4 and central5 in two separate projects the project poms all pointing to the same url and it is only downloading one index. Were the IDs **and** the URLs different in your case? (since this is the only scenario where I could make it download it twice).

You can monitor in real-time which repositories NB is aware of by looking at the services window.

I am also not sure I agree with the conclusion. The same repository can have multiple URLs, as is the case for central for example, so this wouldn't help.

Permissions are per-URL, index storage and identification is per ID.

If a pom makes up a new ID, that ID becomes a new repo from maven POV (although maven seems to be doing some url based deduplication too). (not to mention that it goes against best practice to set the repo in the project pom - it is set by the environment - setting it to central is also pointless since it is already set by the superpom)

**Comment by mbien** [comment]
> After a bit more testing, it seems Netbeans only de-duplicates repositories with the same URL that are currently open

If you don't have any repositories defined, all NB sees are transient repositories taken from the context of your projects and maven defaults, which means deduplication will quit working once there are no duplicates. If you add a repo with right URL manually to the services window, or to .m2/settings.xml it should continue working even if you close projects.

I think we can solve this by automatically adding the remote repository, once fully indexed, to the services view. I tested this and it seems to work fine.

> The different urls for the same repo are a tricky one. But that mainly seems to be the case for central. Maybe a way to register aliases for a repo?

I also added a mapping to convert the repo1 url to apache.org for transitive repositories. I want to get other PRs in first, once done, I will post a link to a dev build here.

> That having repos in the pom goes against best practices may be true, but that doesn't help in the real world when having to deal with external projects...

NB is still an IDE. It does what devs tell it to do if the projects are trusted. Adding magic can be bad - if it starts to swap out URLs and ignore repos it could stop being a useful tool once the behavior is no longer predictable.

**Comment by hylkevds** [comment]
Automatically adding central should fix the disk space issue, most other repositories will be tiny in comparison. Might it be something for the janitor to occasionally check, if there are large mavenindex caches that have not been used in a while?

Thank you for looking into it.

**Comment by mbien** [comment]
> Automatically adding central should fix the disk space issue

it has to work dynamically, since there are also mirrors, e.g: https://storage-download.googleapis.com/maven-central/index.html
Organizations might also have internal mirrors of central.

> Might it be something for the janitor to occasionally check

it would notice abandoned cache dirs, so assuming someone updates to a new NB version from time to time, the old ones would be automatically removed: https://github.com/apache/netbeans/pull/4900 

Maybe this isn't aggressive enough, but I think if we mitigate the duplicates issue a bit, this might be less of a problem for most since there wouldn't be duplicates in the first place.

**Comment by mbien** [comment]
proposed PR is linked above, the CI workflow produces a dev-build for testing, e.g:
https://github.com/apache/netbeans/actions/runs/7020247076?pr=6757 scroll to bottom of the page

please check if this fixes your issue. This would target NB 21 so there is time.

**Comment by hylkevds** [comment]
Some quick tests show that the fix seems to work, but I'll test further in the future. Thanks for the fix!

**Comment by mbien** [comment]
fyi: I chatted on apache slack with maven devs and the google mirrors linked above are the only known public mirrors atm. So its realistically just about a handful of URLs where maven central can be. But any org can run their own repo of course.
