### ISSUE TITLE
Add project statistics

### ISSUE THREAD

**Issue by matthiasblaesing** [apache/netbeans#6836]
### Discussed in https://github.com/apache/netbeans/discussions/6777 (Original issue: https://github.com/apache/netbeans/issues/6776)

<div type='discussions-op-text'>

<sup>Originally posted by **PavelTurk** December  2, 2023</sup>
### Description

Currently NB doesn't provide any project statistics. At the same time IntelliJ has  [this one](https://plugins.jetbrains.com/plugin/4509-statistic) with 1,915,900 Downloads (I don't know if it's true). So, I suggest to add such feature to NB:

- must separate files by type (java, xml, css etc)
- must allow to exclude files/directories (node_modules, for example)
- must provide easy access to biggest/smallest files

I would suggest to do this feature this way. Right click -> Project Statistics or main menu Source/Tools -> Project Statistics

After that there must be window with tabs. The first tab is general, all others are by file type - java, xml, etc.

General tab contains the following table, with all column header sorting:

```
                      file     file     total     blank     comment     code
Language              count    size     lines     lines     lines       lines
-------------------------------------------------------------------------------
Java                   100     200KB     1200      300       400        500   
XML                     20     100KB      600      100       200        300    
-------------------------------------------------------------------------------
Total:                 120     300KB     1800      400       600        800
```
Java tab contains the following table, with all column header sorting:

```
                       file     total     blank     comment     code
Language               size     lines     lines     lines       lines
-----------------------------------------------------------------------
ClassA                 10KB       100        20        30         50   
ClassB                 20KB       200        40        60        100
......   
-----------------------------------------------------------------------
Total:                200KB      1200       300       400        500
```

To make it more interesting it is possible to give percents, for example

```
ClassB                 20KB       200    40(20%)    60(30%)   100(50%)
```

### Why in NetBeans?

1. Although there are different tools outside NB such as maven/gradle reporting plugins, [cloc](https://github.com/AlDanial/cloc) etc it is always better to have it inside IDE - it is both more convenient and gives more opportunities. For example - project -> right click -> statistics show biggest files, double click to open the file.
2. Such feature is very popular - cloc has 17k stars; IntelliJ statistics plugin 1,915,900 Downloads with v.1 release in 2009 and v.4.2.7 released in 2023; this [question about NB statistic support](https://stackoverflow.com/questions/10661636/how-to-count-lines-in-a-netbeans-project) on SO has 42k view and 35 upvotes.
</div>

**Comment by mbien** [comment]
this functionality does already exist in maven plugins for example, to name a one which tries to replicate the output of the `cloc` tool, simply run this in any maven project and you have output very similar to cloc:
```
mvn io.github.orhankupusoglu:sloc-maven-plugin:sloc
```
Every project host, such as github, gitlab, bitbucket etc does also provide comparable code stats dashboards by default - you can't really escape it. There are even services which do nothing else but to generate stats.

As I said in the initial discussion on the mailing list which moved to an issue and was then again moved to a gh discussion: this is a very good usecase for a third party plugin in my opinion (just like the mentioned intellij plugin), which could integrate tools like `sloc-maven-plugin` and simply run them in the repo, or add a hint which injects this into mvn/gradle projects (for example) (even easier to implement), or actually reimplement it in another way. NetBeans was made to be extended!

I wouldn't want to see this implemented in NB, since this would be a clear case of the "not invented here". We have enough to maintain already. Even intellij didn't implement it in the core, but waited till it was available as a plugin instead. My guess is that this feature is fairly niche and has low relevance for most projects, but if you need it for a slide of a presentation, its good to know a place which can generate those stats.

Beside that I think this feature would fit very well to a plugin on the plugin portal, there is also no interest from the user who requested this feature to implement it, and also that no committer indicated the will to implement it, I see no real point to track this as an issue (there already is a discussion thread and a mailing list thread).

NetBeans is a community project, we should only track things which someone wants to implement, or at the minimum where we agree that we should implement it at some point in future, the issue tracker is no wish list.

**Comment by matthiasblaesing** [comment]
Ah whatever. I had no intention to get into a fight. So close again. I would like to have seen this in the discussion instead of here though.

**Comment by mbien** [comment]
> I would like to have seen this in the discussion instead of here though.

https://lists.apache.org/thread/0msx9b26nbhl4oyw19r7wyf1hn55x54q

let me quote the relevant part of my reply from the original mail thread:

> if you change your mind and would like to implement it I can leave the 
issue open, but a feature like this would fit the plugin delivery method 
even better in my opinion - so I still don't see a reason to track it on 
the NB issue tracker.


to repeat it in other words: if any committer/contributor is actually willing to implement it and maintain it, by all means leave the issue open. If the discussion did not result in anyone wanting to implement it -> please leave it closed, the issue tracker is not a wish list.

No hard feelings - lets try to keep the issue tracker clean as we promised to do, we have the old jira as bad example of something nobody wanted to use anymore.

**Comment by Chris2011** [comment]
@mbien  My last to cents here because I got just a hikup of your comment. In most of the cases I'm with you and we already had the topic of adding stuff into NetBeans or adding plugins but this comments makes me nervous: "the issue tracker is not a wish list". YES of course it is a wishlist. It is not just for bugs it is also for features/suggestions/wishes, etc. I wanted to wrote more in a discussion chan but maybe doing a blog post about the pros and cons of OSS. Don't get me wrong I love OSS but it has ups and downs but to totally say: we don't want wishes if you don't want to work on it, should not be the right choice for this.

**Comment by neilcsmith-net** [comment]
I'm inclined to agree with @Chris2011 that feature requests with no active committer are fine, as long as the _idea_ itself is not vetoed. But they should be labelled with https://github.com/apache/netbeans/labels/Contribution%20welcome or https://github.com/apache/netbeans/labels/good%20first%20issue as appropriate.  Remembering that the latter shows up on https://github.com/apache/netbeans/contribute

Could also be a good case for a label that states `Plugin candidate` to indicate that we'd prefer a feature be as a plugin.  It's still a starting point for someone looking to contribute something.

Properly labelled issues don't make the issue tracker unclean - it's the number still with https://github.com/apache/netbeans/labels/needs%3Atriage on that do that! :wink:
