### ISSUE TITLE
Customizing Toolbar Can Overflow Without Creating Dropdown

### ISSUE THREAD

**Issue by IanKrL** [apache/netbeans#7000]
### Apache NetBeans version

Apache NetBeans 20

### What happened

When using the Customize Toolbars feature, if the Netbeans window is just larger than the existing toolbars, adding a new toolbar button can cause the buttons to overflow out of the window (the right-most buttons are not displayed) rather than converting to a dropdown as they should.

I suspect there is a slight miscalculation somewhere or an event getting lost such that it doesn’t think it needs the overflow dropdown.

### Language / Project Type / NetBeans Component

All

### How to reproduce

Launch netbeans
Make not fullscreen
Create a new project (I used the default reactjs)
Select View->Toolbars->Use Small Icons
Select View->Toolbars-> `<Select all toolbars>`
Select View->Toolbars->Customize
Move Performance to the far-right of the toolbar space
Resize the window so it's just wider than the existing toolbar buttons so they all just barely fit.
Add a new icon from the Customize Toolbar window into the Performance toolbar.

At this point the existing far-right button slides off the screen, rather than becoming a dropdown as it should. If it works correctly, remove the icon you just added and slightly adjust the width of the window. Try different widths until it fails. Once you have the right window width it should be reliably reproducible, but only certain widths will fail.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 Pro 22H2

### JDK

openjdk 17.0.8 2023-07-18

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

I have been unable to reproduce this problem on Linux. It can be frustrating to reproduce because it will work properly for most window widths, but get it just right and it fails every time.

### Are you willing to submit a pull request?

No

**Comment by IanKrL** [comment]
https://github.com/apache/netbeans/assets/132458829/16b787dc-01af-4cf1-9176-e9049a706638

This video show it happening.

**Comment by neilcsmith-net** [comment]
Does this happen with an alternative Look and Feel?  Be good to know if it's specific to FlatLaf on Windows.

**Comment by IanKrL** [comment]
I can reproduce with Metal and Nimbus as well.

**Comment by mbien** [comment]
the overflow mechanism of the toolbar is only updated when the toolbar is resized. This works most of the time since adding/removing buttons does resize the toolbar, unless it is modified when it already overflows.

The obvious way of fixing this would be to update the overflow when something is added/removed, but the current implementation rebuilds the whole toolbar when something is added/removed and the overflow mechanism itself adds/removes components too. So this is not going to work.

I have a working version which uses invalidate() and rebuilds the toolbar in doLayout() if it is invalid, but I don't like the impl tbh.Toolbars are also used everywhere, there is a risk that this will break something.

**Comment by mbien** [comment]
linked a draft PR targeting NB 22 - I think this might work.
