### ISSUE TITLE
Palette JSF; Wizards "from entity" don't work

### ISSUE THREAD

**Issue by rgrin08** [apache/netbeans#7194]
### Apache NetBeans version

Apache NetBeans 21

### What happened

Maven Web application.
I want to insert a JSF form or a JSF datatable  from entity.
1. Drag and drop "JSF form from entity" into the page.
2. A pop up window "JSF Form From Entity" is displayed.
3. I choose an entity among the entities displayed in the field "Entity". Automatically a "Managed Bean property" is displayed. (with a method that returns the entity)
4. I let the standard template style.
5. Clic on OK.
6. Nothing happens. A new pop up window "JSF Form From Entity" is displayed.

No error message.
The same with "JSF data table from entity".

### Language / Project Type / NetBeans Component

Java Maven Web application project

### How to reproduce

1. Create a Maven Web application.
2. Create a JSF page.
3. Create an entity.
4. Create a CDI bean with a method that returns the entity and a method that returns a list entities.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11 Family 64-bit

### JDK

17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

This problem always occurs.

### Are you willing to submit a pull request?

No

**Comment by rgrin08** [comment]
I forgot to mention that it is a **Jakarta EE 10** application.

**Comment by matthiasblaesing** [comment]
I think this is already fixed in master. I used the nightly build from #7218 (https://github.com/apache/netbeans/pull/7218/checks / https://github.com/apache/netbeans/suites/22293481261/artifacts/1374035463). With that:

1. I started NetBeans with a clean user and cache dir (`netbeans/bin/netbeans --userdir testuserdir --cachedir testcachedir`)
2. Activated the JavaEE Modules (Tools -> Plugins -> Installed -> Java Web and EE, Activate that feature set)
3. Registered GF 5.1.0 as Server (Tools -> Servers), so that a support JavaDB client is present
4. Registered GF 7.0.11 as Server
5. Created a new maven based web project (File -> New Project -> Java with Maven -> Web Application, choose 7.0.11 as server in the wizard, Jakarta EE 10 is automatically chosen then)
6. Generate the Entities by opening the context menu on the project node and choosing New -> Entity Classes from Database, choose "Server Data Source" and choose `jdbc/sample` (should be shipped with GF), Add "PRODUCT_CODE" to tables
7. Checked that the Entity `ProductCode` is generated using the JakartaEE Persistence packages (not javax)
8. Created a JSF page using "New File" wizard with Category "Web" and File Type "JSF Page"
9. In `newjsf.xhtml` I opened the palette and dragged the "JSF Form From Entity" into the xhtml file
10. In the opening dialog I choose the `ProductCode` enttiy, enter "xy" as Managed Bean Property, choose "Standard JavaServer Faces" as Template Style
11. Code is generated:
![image](https://github.com/apache/netbeans/assets/2179736/0b5a2810-7877-477b-ae1e-a65f82a57bc1)

So please retest with the referenced nightly.

**Comment by matthiasblaesing** [comment]
This is supposed to be fixed, reporter did not respond, so closing.
