### ISSUE TITLE
Jakarta Faces: editor does not detect composite components

### ISSUE THREAD

**Issue by FabriSr** [apache/netbeans#7226]
### Apache NetBeans version

Apache NetBeans 21

### What happened

The HTML / XHTML editor does not recognize Jakarta Faces composite components. 

### How to reproduce

1 - Open the demo project using NetBeans: [faces-cc-error.zip](https://github.com/apache/netbeans/files/14830871/faces-cc-error.zip);

2 - Open the project's "index.xhtml";

3 - The tag "<myComposite:myCompositeComponent />" is detected as an error with the hint: "The component library Composite Components does not contain component myCompositeComponent";

4 - Run the application executing "liberty dev" maven goal;

5 - Open "http://localhost:9080/index.xhtml": the composite component is rendered as expected

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Oracle Linux

### JDK

OpenJDK 11

### Apache NetBeans packaging

Other

### Anything else

Installed using RPM package

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
@FabriSr the problem here is not that the editor does not detect composite components, it is also not, that with the JavaEE-> JakartaEE transition, but the problem is, that the composite components are not in the default `resources` folder. 

The sample project (thank you, that was very helpful!) uses the context parameter `jakarta.faces.WEBAPP_RESOURCES_DIRECTORY` to change the location of the resources folder to `WEB-INF/resources`, however the indexer only recognized the context parameter `javax.faces.WEBAPP_RESOURCES_DIRECTORY`. This is another fallout of the JavaEE->JakartaEE renaming mess.

The fix though is trivial. Please check the change suggested in #7236.

A nightly build is available from the checks page (see "Artifacts" dropdown, https://github.com/apache/netbeans/pull/7236/checks) or directly via https://github.com/apache/netbeans/suites/22395136198/artifacts/1382458648).

**Comment by FabriSr** [comment]
I ran the suggested build and opened the sample project but still showing as an error:

![image](https://github.com/apache/netbeans/assets/82968035/c4c75dd8-aa13-4ac7-9550-681147837b21)

**Comment by matthiasblaesing** [comment]
@FabriSr was this done with a clean user and cache dir? I tested exactly this scenario.

**Comment by FabriSr** [comment]
It worked! Thank you!

**Comment by matthiasblaesing** [comment]
Great - but did you change anything?

**Comment by FabriSr** [comment]
I did as you suggested: clean user and cache dir.

**Comment by matthiasblaesing** [comment]
Thanks will merge in the next few days.
