### ISSUE TITLE
Can't start new file nor project

### ISSUE THREAD

**Issue by cho-mik** [apache/netbeans#7399]
### Apache NetBeans version

Apache NetBeans 21

### What happened

I can't create new project. I try "new project", then I select "Jave with Maven" and "Java application". I click "next" it goes to "finding feature" and displays nothing. Only "cancel" is active.
![obraz](https://github.com/apache/netbeans/assets/170624109/ecff4ec5-1bf7-407d-919d-cf99b7bb869d)

[messages.log](https://github.com/apache/netbeans/files/15431196/messages.log)

### How to reproduce

"new project", "Jave with Maven" "Java application". "next" 

### Did this work correctly in an earlier version?

Apache NetBeans 19

### Operating System

Windows 10

### JDK

JDK 22

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
```
INFO [org.netbeans.Stamps]: cannot rename (#0): C:\Users\spamm\AppData\Local\NetBeans\Cache\21\all-layers.dat
...
WARNING [org.netbeans.Stamps]: Error saving cache C:\Users\spamm\AppData\Local\NetBeans\Cache\21\all-layers.dat
INFO [org.netbeans.Stamps]: Could not delete: C:\Users\spamm\AppData\Local\NetBeans\Cache\21\all-layers.dat
java.io.IOException: Could not delete: C:\Users\spamm\AppData\Local\NetBeans\Cache\21\all-layers.dat
	at org.netbeans.Stamps.deleteCache(Stamps.java:515)
	at org.netbeans.Stamps.access$200(Stamps.java:69)
[catch] at org.netbeans.Stamps$Store.store(Stamps.java:709)
	at org.netbeans.Stamps$Worker.run(Stamps.java:887)
```

NetBeans can't delete that file for some reason. You could try to restart your system to make sure all file locks are released, then remove this folder: `C:\Users\spamm\AppData\Local\NetBeans\Cache\21`.

Once done NB should hopefully work again.

**Comment by neilcsmith-net** [comment]
@mbien stamp file aspect is odd, but this looks more like the issue fixed in #7334

**Comment by mbien** [comment]
@neilcsmith-net you are right. It was my first thought too but I got distracted by the exception in the log. `nbjavacapi` module isn't loaded so its the same symptom.

@cho-mik this issue is fixed in NB 22 which should be available next week. If you want to use NB 21 till then, try resetting your config in `C:\Users\spamm\AppData\Roaming\NetBeans\21`. Once you start NetBeans again, create a new maven project right away without opening the plugin manager or the options and all modules should initialize properly.

**Comment by cho-mik** [comment]
Yes, after the restart it works. Thank you.
