### ISSUE TITLE
Broken project tree when I create specific package

### ISSUE THREAD

**Issue by 6PATyCb** [apache/netbeans#7445]
### Apache NetBeans version

Apache NetBeans 22

### What happened

Project tree not working correctly when I create package "roles" in my java maven project. Before create it's looks like:
![изображение](https://github.com/apache/netbeans/assets/33724393/459f46e3-77d5-49bf-b47f-5792e4d3c8d9)
but after create package "roles":
![изображение](https://github.com/apache/netbeans/assets/33724393/362cccb1-76c5-45c7-a5fb-ba681a3e20c7)
I make close project and open it again and project tree changed to this:
![изображение](https://github.com/apache/netbeans/assets/33724393/5f9f6a1d-a1de-4065-a11d-82e712fe9bab)

### Language / Project Type / NetBeans Component

Java maven project

### How to reproduce

Allready broken project in attachment
[lift_ui.zip](https://github.com/user-attachments/files/15739153/lift_ui.zip)
To repair it you could delete directory <code>src\main\java\ru\java_inside\lift_ui\roles</code> and reopen project in NB.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

Liberica JDK 21x64

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment]
Not reproducible for me (on linux though). Please provide the message.log, maybe something is visible there. 
See: https://stackoverflow.com/questions/50462124/netbeans-where-to-find-the-ide-log

**Comment by 6PATyCb** [comment]
> Not reproducible for me (on linux though). Please provide the message.log, maybe something is visible there. See: https://stackoverflow.com/questions/50462124/netbeans-where-to-find-the-ide-log

Log collected after open broken project

[messages.zip](https://github.com/user-attachments/files/15751653/messages.zip)

**Comment by matthiasblaesing** [comment]
Sorry, the `message.log` does show nothing out of the ordinary. However I saw plugins installed, not coming from the main distribution. So given, that it is not reproducible for me, I suspect their involvement.

You can try to run NetBeans with a fresh `userdir`, so that you can try to reproduce with a pure installation. Run from `cmd`: `<path_to_nb>/bin/netbeans64.exe --userdir c:/temp/testuserdir --cachedir c:/temp/testcachedir`. You should ensure, that the folder `c:/temp` exists and when you want to cleanup just delete the two specified directories. You can then test with a clean installation and install you modules, adjust settings and see when things break.

**Comment by 6PATyCb** [comment]
Thanks for the help! I found an old third party plugin that, when disabled, does not reproduce my issue. I might even be able to find its source code to dig deeper. Sorry for wasting your time, I should have thought to disable all plugins first before writing a bug report.

**Comment by matthiasblaesing** [comment]
Thank you for following up with a check an solution!
