### ISSUE TITLE
Move from maven 3.9.7 to 3.9.8

### ISSUE THREAD

**Issue by PavelTurk** [apache/netbeans#7450]
### Description

Today I wanted to test NB build dev-49f55215939b825591683d3257d5d969b598d399 but I couldn't build my javafx projects because it uses maven 3.9.7 that has a serious bug:
https://stackoverflow.com/questions/78542808/maven-project-fails-to-resolve-javafx-dependencies
https://issues.apache.org/jira/browse/MNG-8131 , 
so, when it is fixed it is necessary to update maven version.

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
There is a plan to do this assuming it's released before the next freeze. We always try to ship the latest release.

NetBeans supports using mvnw, and it's a good idea to control the version of Maven used in your project.

**Comment by mbien** [comment]
NetBeans 22 bundles maven 3.9.6.

NetBeans 23 will likely use the latest maven build which is available when our release phase begins. We are often testing staged maven builds and participate in the vote itself, if time permits I will do this for 3.9.8 too.

Regarding 3.9.7: this looks more like a buggy pom on javafx side and less like a maven bug to me. The proposed fix is to turn the error into a warning for the next update release so that it behaves like 3.9.6 did, but with more yellow in the log.

**Comment by mbien** [comment]
https://github.com/apache/netbeans/pull/7468
