### ISSUE TITLE
Netbeans unable to detect when Jboss EAP 8.0 is running

### ISSUE THREAD

**Issue by HowardUngar** [apache/netbeans#7521]
### Apache NetBeans version

Apache NetBeans 22

### What happened

Console window shows server started successfully.  But Netbeans icons never change from enabling "Start the Server" to "Stop the Server"

### How to reproduce

Added new server.  Right-click on newly added server and select "Start in Debug Mode".

Note that this was working with JBoss EAP 8.0 Beta and JBoss EAP 7.x.  

![add_server](https://github.com/apache/netbeans/assets/19477177/a769f845-440d-44b9-bb6f-a37d43dfe349)
![start-server](https://github.com/apache/netbeans/assets/19477177/58aab743-cac2-4962-8105-75930d201940)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Tried both Mac OS and Windows

### JDK

java-21-openjdk-21.0.3.0.9-1.win.jdk.x86_64

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

Yes

**Comment by marcuscf** [comment]
Same behavior with JBoss EAP **6.4.22** (NetBeans 22, JDK 17). You can add JBoss as WildFly and it'll start just fine but you can't interact with it (deploy a .war, stop it, etc.) because NetBeans doesn't recognize it as started. You can stop it by closing NetBeans, though.

Last time I know for sure it worked well was on NetBeans 8.2, before the Apache NetBeans era. I have tested NetBeans 13 too and it behaves the same as NetBeans 22. Not sure if it ever worked on other versions.
