### ISSUE TITLE
Hovering over constructor and it's integer arguments showing wrong signature

### ISSUE THREAD

**Issue by subhash-arabhi** [apache/netbeans#7653]
### Apache NetBeans version

Apache NetBeans 22

### What happened

When hovering over the constructor, it shows the class signature. Hovering over the first letter of it's integer argument shows the method signature.

### How to reproduce

<img width="558" alt="Screenshot 2024-08-09 at 4 34 53 PM" src="https://github.com/user-attachments/assets/cf130b25-2aaa-4d79-b0ab-86d725c5115e">
<img width="748" alt="Screenshot 2024-08-09 at 4 35 15 PM" src="https://github.com/user-attachments/assets/e74975e3-802f-448e-a054-b020b1850515">

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS

### JDK

openjdk 22.0.1, jdk 17

### Apache NetBeans packaging

Apache VSNetBeans for VSCode

### Are you willing to submit a pull request?

Yes

**Comment by mbien** [comment]
@subhash-arabhi please add a small reproducer snippet next time additional to screenshots

quick test using:
```java
public class Mavenproject1 {

    /**
     * Sample class.
     * @author mbien
     */
    static class Sample {
        /**
         * Sample constructor.
         * @param hello greeting
         * @param par a number
         */
        public Sample(String hello, int par) {
        }
    }

    public static void main(String[] args) {
        Sample sample = new Sample("hello", 42);
    }

}
```
parts of it are also reproducible in NB 22, e.g completion shows class doc instead of constructor doc:

![image](https://github.com/user-attachments/assets/44152087-10b4-4eaf-8ab8-1a34546ccae7)

however, `ctrl+mouse hover` does produce the expected results:
![image](https://github.com/user-attachments/assets/0b475b37-1076-4e69-9dfb-c8c3e2932a3f)

**Comment by mbien** [comment]
added https://github.com/apache/netbeans/labels/VSCode%20Extension label since I don't think this affects NB, unless I don't understand the issue.
