### ISSUE TITLE
Editor erroneously marks error "not supported in -source 17" on switch code with type pattern

### ISSUE THREAD

**Issue by jjazzboss** [apache/netbeans#7702]
### Apache NetBeans version

Apache NetBeans 22

### What happened

Code with type/guarded pattern in switch compiles OK, but editor marks an error "patterns in switch statement are not supported in -source 17"

### How to reproduce

Create a java 17 code with type patterns, e.g.
```
        switch (navCli)
        {
            case CLI_Ending cli && cli.getData().isStartType()  -> { ... }
            case default ->   {}
        }
```
My pom.xml configures the maven-compiler plugin to use release and source=17.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Win 11

### JDK

Adoptium JDK 17 x64

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
A NetBeans release can only support the latest preview (in case it wasn't released yet) or the final version of a language feature. Which means you would have to use the final version of JDK 21+ (https://openjdk.org/projects/jdk/21/).

javac itself does only support the latest version, so your code snippet will not compile on JDK 21 for example. Since the java editor is using a current snapshot of javac at the time of release, it does also only have access to one implementation at a time. (pattern matching in switch had 4 previews + release)

options:
 - update your project to JDK 21+
 - try using NB 17 which shipped with nb-javac based on javac 19 if my notes are correct. It looks like preview 3 supported the syntax you are using still. Preview 4 changed it, but I didn't look at it in detail.
 - don't use preview features, unless you are willing to keep upgrading to the latest jdk / take the risk of having to make changes

related: https://github.com/apache/netbeans/discussions/7620
