### ISSUE TITLE
Option to hide the "mini welcome screen"?

### ISSUE THREAD

**Issue by vbickov** [apache/netbeans#7920]
### Description

The NetBeans already has a welcome screen with all the necessary links and shortcuts for newbies. I've been using this IDE for 12 hours a day since 2006. Why do you think I need to see this small version of the welcome screen every time I close all tabs? :

![image](https://github.com/user-attachments/assets/887d221d-0429-4706-af05-a7c552ea816e)

### Use case/motivation

A professional developer does not need/want to see your logo and shortcuts all the time. 

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
This is not intended to be a welcome screen, or aimed at "newbies".  Personally I use it all the time.  The dashboard replaced the welcome screen, and is also not just aimed at new users.

Both were designed to allow configuration by users and platform developers.  However, there is not currently a UI for this.  It's been on my own to-do list since adding these, but I have little time to work on NetBeans right now.  Maybe someone else will pick this task up.

In the interim, you can follow the instructions at https://github.com/apache/netbeans/pull/5591#issuecomment-2200422010 to hide if you must.

**Comment by vbickov** [comment]
Thank you for the instructions. I do not know what this is intended to be, but looking at its functionality, this is a small version of the welcome screen. Please consider doing everyone a favor by adding an option to the settings.

**Comment by neilcsmith-net** [comment]
It's quick access to common actions.  It is not intended to be a small version of the welcome screen (and neither is dashboard for that matter).  As someone who has used NetBeans for a similar length of time to you, I find I use the quick actions all the time.  I never use the toolbar, shall we remove that instead?!

A PR to customise the actions (which would include the option to have nothing) would be welcomed.

**Comment by vbickov** [comment]
You can customize or hide the toolbar, and you do not need to manually add an empty file to an unnamed folder to get rid of it. I requested an option to hide it (not remove it completely). As it was already pointed out in https://github.com/apache/netbeans/pull/5591#issuecomment-2200422010 , an empty editor is supposed to be empty. IMHO.

**Comment by neilcsmith-net** [comment]
The background actions are customizable in a similar way to the toolbars, using the config file system.  That is how you can hide them in the first place.  It was a key criteria in adapting #5591 for inclusion, which I personally took on because I also wanted to use the feature in 2 platform applications.

What there is not at present is a UI to control the config file system configuration of these.  You are welcome to work on one.  Given I like the IDE as it is, and the current implementation meets my platform requirements, it's certainly not high on my own to-do list.  If you or anyone else wants guidance on how to implement this, I'm sure we can provide support to do so.

Have opened #7927 and added link to the default IDE configuration, which also shows where in the file system this is configured.

**Comment by Chris2011** [comment]
> You can customize or hide the toolbar, and you do not need to manually add an empty file to an unnamed folder to get rid of it. I requested an option to hide it (not remove it completely). As it was already pointed out in [#5591 (comment)](https://github.com/apache/netbeans/pull/5591#issuecomment-2200422010) , an empty editor is supposed to be empty. IMHO.

I totally disaggree with the "empty editor" I think first the problem is with the wording, It is not an editor IMHO the edior is a tab with content inside. This is the background of an empty editor or the area where editors can be placed. If you have an empty editor, it is just a empty tab.

Second I aggree with more options (yes makes it more comples but this is the reality someone wants it, someone doesn't want it). So yes an option to hide this should be good. For me I also use NB since 2013 I guess but for my daily work, unfortunately I need to move to another IDE but this is another point. Why I say this in this context? We have more stuff here to do and to make it more professional or also to make it more stable as before. But it is our work to do this. But hey @vbickov there was also another issue created which talks about a UI to change the behaviour FYI.
