### ISSUE TITLE
Minimap in SourceCode Editor window

### ISSUE THREAD

**Issue by wumpz** [apache/netbeans#7967]
### Description

Are there any plans to add a minimap / source code outline view for a source code editor? This was quite helpful. I know there is some outdated stuff around.  Or is there an active plugin I do not know?

### Are you willing to submit a pull request?

No

**Comment by Chris2011** [comment]
The one from @markiewb is not working anfortunately, I wanted to have a look but lacl of time. And another one is this here: https://gitlab.com/mcheung63/netbeans-minimap maybe you can try this first.

**Comment by Chris2011** [comment]
And TBH there is no plan afaik to do this, I wanted to implemented it as well, but also just as a plugin. Sooner or later on my Priority list of 9277294 Tasks

**Comment by wumpz** [comment]
Where is the source code for @markiewb  plugin?

**Comment by Chris2011** [comment]
> Where is the source code for @markiewb plugin?

https://github.com/Chris2011/nb-codeoutline

**Comment by wumpz** [comment]
I made a PR on nb-codeoutline: https://github.com/Chris2011/nb-codeoutline/pull/44. Now it runs using Netbeans 23.

However, IMHO one should remove this bluej dependencies.

**Comment by Chris2011** [comment]
@wumpz nice, I will have a look on the weekend :). So if you would like to change this, do it.

My idea for a new impl was:
* Add SidebarFactory to register on EAST or WEST via option
* Clone the current opened with the content, make it readonly, decrease font size and add this into sdebar
* Fix bugs :D

I dunno what bugs will be or misbehavior but this makes more sense IMHO instead of using bluej

**Comment by Chris2011** [comment]
So nb-codeoutline can be found here, which works for NetBeans 23: https://github.com/Chris2011/nb-codeoutline/releases/tag/1.4.0 @wumpz thank you very much for your support :). I think we can close this here.
