### ISSUE TITLE
Minor improvements to new Usages preview panel (NB24)

### ISSUE THREAD

**Issue by jjazzboss** [apache/netbeans#8068]
### Description

Attached image is what I get with Usages.  I can't read the beginning of left panel so each time (except if the first usage line found is short) I have to scroll on the left. 
![2024-12-17 20_55_00-MusicControl - Apache NetBeans IDE 24](https://github.com/user-attachments/assets/b19392e1-adee-48a3-a2ee-8feafe44d317)

### Use case/motivation

Scrollbar of the left panel should be forced to the left. 
Horizontal split position between left/right usage panels should be saved and reused for next Usages.

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment]
this is behavior is shared between all trees. The scrollpane will try to keep the node in the viewport if the selection changes.

The reason why it is more noticeable in the usages window is likely because the nodes can contain longer lines, this pretty much guarantees that the viewport moves if the selection changes.

I can reproduce the same behavior in the projects tree or refactoring preview window etc. I am sure we can come up with something but we have to be careful to not introduce other bugs.

**Comment by jjazzboss** [comment]
If it's easier, just saving the split position and reuse it would be another way to solve this.  It might seem a minor thing, but doing 30 times scroll+move split bar is really irritating at the end...

**Comment by mbien** [comment]
yeah, UI persistence for the find-usages splitter needs to be implemented. The search results window https://github.com/apache/netbeans/pull/7779 does have it but we overlooked it for find-usages https://github.com/apache/netbeans/pull/7694.

**Comment by mbien** [comment]
@jjazzboss implemented the tree navigation change in https://github.com/apache/netbeans/pull/8089, dev-build for testing purposes is here: https://github.com/apache/netbeans/actions/runs/12473627487/artifacts/2357510860
